### ISSUE TITLE
need a tutorial

### ISSUE THREAD

**Issue by NomNomAQP** [pepzwee/node-csgo-web-tradebot#100]
Please a tutorial for install in vps o vultr, digitalocenan?

**Comment by FreddyFish** [comment]
No, and there will not be any. If you do not know how to install this, you should probably not use it.

**Comment by pepzwee** [comment]
There will possibly be a tutorial available on SteamApis.com soon.. with a lot of warnings against using this script unless you understand the code.

**Comment by pepzwee** [comment]
Tutorial: https://steamapis.com/projects/node-csgo-web-tradebot

**Comment by NomNomAQP** [comment]
Thankssss !! :')

**Comment by NomNomAQP** [comment]
Hi,

sry again need u help

view my pastebin please: https://pastebin.com/ikyXU5vH

2017-09-30 12:11 GMT-05:00 Bryan Paz Ccopa <bryanpc123@gmail.com>:

**Comment by FreddyFish** [comment]
Add 5 USD / EUR to the account, to get access to the SteamAPI on your bot account.

**Comment by NomNomAQP** [comment]
Recharge in steam API ando any more ? Or select any plan upgrade?

**Comment by FreddyFish** [comment]
No, not steamapis.com. im talking about the steam API.

**Comment by NomNomAQP** [comment]
My acc is free, with 15dolars in founds ando ítems lv 11 steam need more ?
