### ISSUE TITLE
FloatChecker:Error

### ISSUE THREAD

**Issue by KronosR97** [pepzwee/node-csgo-web-tradebot#101]
Hello!

im getting this error in the console

 [FloatChecker:Error] Could not get inventory for "bot_1", can't set floats.

and the bot inventory isnt loading, can you guys help me?

**Comment by DenDP** [comment]
You need the API's from steamapis.com for market/items and steam/inventory. Also you need a bot who is not limited on steam (added 5$ to its account)

**Comment by JorgeReyes97** [comment]
ok, thank you @DenDP :)

**Comment by JorgeReyes97** [comment]
im having the same error, and my key have the market/items and steam/inventory endpoints

**Comment by pepzwee** [comment]
Do you have CS:GO on the bot account?

**Comment by JorgeReyes97** [comment]
No, the account doesnt have CSGO, and the steam id 76561198277855195

**Comment by pepzwee** [comment]
Okay, and the inventories are not loading on the website?

**Comment by KronosR97** [comment]
only the bot inventory

**Comment by pepzwee** [comment]
Did you set the bot steamID64 in the config file?

**Comment by KronosR97** [comment]
now is working, a fucking space at the end in the steamID var was the problem xD

steamID64: '76561198382870240 '

**Comment by mogadanez** [comment]
Have same issue.

Checklist:

* purchased steamapis  access
* added funds on account
* have csgo on bot account
* fill bot auth.

Logs:

> Bot (bot_1) has been logged-in.
[!] Website server is online.
[!] Socket server is online.
[!] Prices are updated.
[FloatChecker:Error] Could not get inventory for "bot_1", can't set floats.
[!] All bots online.

In UI: 

>  Something went wrong.. please try again! (400)


Should steamApiKey be  one of the Bots? or can be separate account?

**Comment by FreddyFish** [comment]
@mogadanez - Try using the Steam API key from your bot account.
Also have you created the/polls/bot_1.json file?

**Comment by mogadanez** [comment]
yes i  have /polls/bot_1.json
API  key  from another "root" account is OK, otherwise  how it work with multiple bots.

problem is  in hiding errors  without loging.
I was debug into inv.js: getInventory() - and found real error code

so i have 2 another points to checklist:
* inventory should be switched to public
* bot should have  items, which indirectly mean  that account should be at least 15 days old.



P.S. I'm,  go to  rewrite code a little in own branch with Promises
