### ISSUE TITLE
Price $-0.00

### ISSUE THREAD

**Issue by trylol** [pepzwee/node-csgo-web-tradebot#102]
When i pick 3 items in bot inventory and unpick it on  bots offer price on Bot`s offer showing $-0.00.
Please, fix this bug.

**Comment by FreddyFish** [comment]
What is the problem? The value is still 0.

**Comment by pepzwee** [comment]
Does that issue break anything fundamental on the website? If it's really bothering you the step to fix this issue is ``Math.abs()`` the price values.
