### ISSUE TITLE
hi two factor code

### ISSUE THREAD

**Issue by TonyS95** [pepzwee/node-csgo-web-tradebot#103]
basically
its impossible to get two factor code when u go in secret steamdesktopauthenticator because on latest version when u go to mafile  my steamid it only pop ups the long code

**Comment by TonyS95** [comment]
found the issue close this

**Comment by FreddyFish** [comment]
Is the file decrypted?

**Comment by FreddyFish** [comment]
Close it yourself.

**Comment by TonyS95** [comment]
wat u mean

**Comment by TonyS95** [comment]
and were do i fnd the factor code

**Comment by TonyS95** [comment]
how do i close
