### ISSUE TITLE
Hi do i have to put with apikey

### ISSUE THREAD

**Issue by TonyS95** [pepzwee/node-csgo-web-tradebot#104]
the steambot apikey or my personal steam account api key

**Comment by FreddyFish** [comment]
For Steamapis.com it does not matter.
For Steam API i would use the one from the bot. Then you are also sure, that the bot has access to everything.

**Comment by TonyS95** [comment]
ow thanks mate  i can't find the identity_secret value in steamdesktopauth

**Comment by FreddyFish** [comment]
Its there. In the end of the file.
