### ISSUE TITLE
Steam login issue

### ISSUE THREAD

**Issue by TonyS95** [pepzwee/node-csgo-web-tradebot#105]
When i press sign in through steam this happens in the picture i have put all of my steam api key's
![capture](https://user-images.githubusercontent.com/32432159/31054574-098f368a-a6ad-11e7-84da-552f08f8c4f2.PNG)

**Comment by FreddyFish** [comment]
Disable apache or ngnix.

**Comment by TonyS95** [comment]
how do i do it

**Comment by TonyS95** [comment]
am using apache

**Comment by FreddyFish** [comment]
Sudo apt-get remove apache2

**Comment by TonyS95** [comment]
yeah did that

**Comment by FreddyFish** [comment]
Great, it should work now.

**Comment by TonyS95** [comment]
site can't be reached

**Comment by FreddyFish** [comment]
Did you forget to run the index file?

**Comment by TonyS95** [comment]
wat do u mean

**Comment by FreddyFish** [comment]
If you have no experience with node.js you should probably not run this script.

Start it with node index.js

**Comment by TonyS95** [comment]
is there a tutorial how to install i'll try to install again

**Comment by TonyS95** [comment]
yeah i have no idea about scripting

**Comment by FreddyFish** [comment]
Yes. Its in the readme.

**Comment by TonyS95** [comment]
can u send me a link cuz it ant no in the read me

**Comment by FreddyFish** [comment]
https://github.com/pepzwee/node-csgo-web-tradebot/blob/master/README.md

**Comment by TonyS95** [comment]
ow probably it didin't say cuz i download from a youtuber

**Comment by FreddyFish** [comment]
Do not download this from untrusted sources. The only place you should be getting this from is here. You are probably good though, but be careful.

**Comment by TonyS95** [comment]
how do i get nginx the command sorry for asking so much :(

**Comment by TonyS95** [comment]
am new like new to this stuff

**Comment by FreddyFish** [comment]
The command for ngnix? What do you mean?

**Comment by TonyS95** [comment]
like install it

**Comment by FreddyFish** [comment]
Follow the tutorial, and it should be done within a few minutes.

**Comment by TonyS95** [comment]
it doesn't say how to install nginx

**Comment by FreddyFish** [comment]
What would you need ngnix for? Ngnix is not required?

**Comment by TonyS95** [comment]
aw u don't get it
