### ISSUE TITLE
 i can't find identity_secret

### ISSUE THREAD

**Issue by TonyS95** [pepzwee/node-csgo-web-tradebot#107]
i can't find identity_secret

**Comment by ozanbudak** [comment]
Use this to get your identity and shared secret values: https://github.com/Jessecar96/SteamDesktopAuthenticator

**Comment by TonyS95** [comment]
ik but when go to mafiles my steamid it only shows me sected but not identity-secret
e

**Comment by ozanbudak** [comment]
If you did the instructions on steamdesktopauthenticator correct and at least one time you run exe properly there should be a mafile like steamidofbot.maFile and in that file there should be value identity_secret:

**Comment by TonyS95** [comment]
wat u mean the steam d .mafile in themafila folder

**Comment by ozanbudak** [comment]
Inside mafiles folder there should be a file like "76561198387703833.maFile"

**Comment by TonyS95** [comment]
ye

**Comment by TonyS95** [comment]
i opened it and it only has shared value

**Comment by TonyS95** [comment]
so
