### ISSUE TITLE
Need help please :c

### ISSUE THREAD

**Issue by NomNomAQP** [pepzwee/node-csgo-web-tradebot#110]
need help :c 

whats is the problem please !! 

![sin titulo](https://user-images.githubusercontent.com/32375910/31060909-ba19fa7a-a6e0-11e7-97df-bd57beaa45ee.png)

**Comment by pepzwee** [comment]
These are the possible issues:

1. Invalid ``SteamApisKey``
2. Don't have enough funds on https://steamapis.com
3. You have not enabled ``steam/inventory`` endpoint
