### ISSUE TITLE
Something went wrong.. please try again! (402)

### ISSUE THREAD

**Issue by itzMal** [pepzwee/node-csgo-web-tradebot#112]
### Expected behavior
Able to load my skins in my inventory!
### Actual behavior
It says in a red box "Something went wrong.. please try again! (402)" and doesn't load any of the skins.
### Steps to reproduce the behavior
Not using the SteamApis key (not able to afford it right now.)
### Other
1. [Operating System]: Ubuntu 16.04.3
2. [Node.js version]: v6.11.3
3. [How did you start the script]: node index,js

So, I'm pretty sure I know the problem; I don't use the SteamApis key. I don't have much experience with API keys in general, and I really don't know how to switch from one site such as SteamApis to another site such as CSGOFast. If someone could help me switch API keys or help me set it up so that maybe BitSkins or CSGOFast would work for an API key, that would be wonderful.

If anyone wants to know the error and hasn't seen it already, it happens when the site tries to load the inventory:

Something went wrong.. please try again! (402)

(Also, in the console for the bot, it says this: [FloatChecker:Error] Could not get inventory for "bot_1", can't set floats.)

**Comment by FreddyFish** [comment]
#110  - Same issue. :)
I'm not sure what you are on about, but i'm pretty sure it's not possible to load inventories through the csgofast API. It's possible to get the price though. If you want you can check in the history of /lib/prices.js as grabbing prices from csgofast was a thing a few months ago.

**Comment by pepzwee** [comment]
Correct, there's no free API for inventory loading unless you use the official steam URL which can get you rate-limited rather quickly.

**Comment by coooool123** [comment]
Is it more accurate than apis?

**Comment by iDefineHD** [comment]
@coooool123 its the same output. Just that the api services provide a lot more requests without a "rate limit" like steam does. I mean they do have one. But nowhere as bad as official api call.
