### ISSUE TITLE
Trade status: {}

### ISSUE THREAD

**Issue by DarkAngel2389** [pepzwee/node-csgo-web-tradebot#115]
when i  click on Trade the website create a pop-up with the message
Trade status:
{}
![problem](https://user-images.githubusercontent.com/27443407/32010740-f5fa3e12-b9b2-11e7-94fb-3a4f50afa6f9.JPG)

**Comment by FreddyFish** [comment]
Bot does not have access to the Steam API. Deposit 5 EUR to your steam account.

**Comment by DarkAngel2389** [comment]
i have a lots of game on the steam account of the bot

**Comment by FreddyFish** [comment]
Doesnt matter. Did you deposit money to the account?

**Comment by DarkAngel2389** [comment]
now?

**Comment by FreddyFish** [comment]
No, in general. Did you ever deposit money to it?

**Comment by DarkAngel2389** [comment]
yes

**Comment by FreddyFish** [comment]
Did you obtain the Steam API key using your bot account?

**Comment by DarkAngel2389** [comment]
no

**Comment by FreddyFish** [comment]
Go do that.

**Comment by DarkAngel2389** [comment]
i need to buy the new apikey?

**Comment by FreddyFish** [comment]
The API key is free to get.
Its the Steam API key, not the steamapis.com key.

**Comment by DarkAngel2389** [comment]
ah

**Comment by DarkAngel2389** [comment]
Something went wrong.. please try again! (401)

**Comment by DarkAngel2389** [comment]
i have this problem

**Comment by DarkAngel2389** [comment]
man,are u here?

**Comment by DarkAngel2389** [comment]
ok,now i can see the inventory but i have the same problem
Trade status: {}

**Comment by DarkAngel2389** [comment]
or : Could not get a price for item(s). Trade has been cancelled.

**Comment by DarkAngel2389** [comment]
@FreddyFish ok,i fix the bug (Could not get a price for item(s). Trade has been cancelled.).
Now i have this: Trade status: {}

**Comment by DarkAngel2389** [comment]
Man,help me

**Comment by pepzwee** [comment]
User didn't have the ``polls`` folder and ``bot_1.json`` file.
