### ISSUE TITLE
Auth/Steam

### ISSUE THREAD

**Issue by cenoura008** [pepzwee/node-csgo-web-tradebot#116]
Im getting the following error when i try to log in on steam

The requested URL /auth/steam was not found on this server.

And on console I get this:

![dfsfdfd](https://user-images.githubusercontent.com/33322215/32332026-baa14b48-bfe4-11e7-9c0b-4ee282d8007c.PNG)

**Comment by pepzwee** [comment]
Follow tutorial correctly, you have not installed the dependencies.
https://steamapis.com/projects/node-csgo-web-tradebot
