### ISSUE TITLE
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

### ISSUE THREAD

**Issue by Diaper1** [pepzwee/node-csgo-web-tradebot#117]
### Expected behavior
Log into with Steam
### Actual behavior
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
### Steps to reproduce the behavior
Following all steps in tutorial.
### Other
1. [Operating System]: <Ubuntu 16.04
2. [Node.js version]: <here>
3. [How did you start the script]: <Putty>

### Error Stack
Thanks for the Help

**Comment by FreddyFish** [comment]
Remove apache.

**Comment by Diaper1** [comment]
sudo systemctl stop apache2
Failed to stop apache2.service: Unit apache2.service not loaded.

**Comment by Diaper1** [comment]
Nvm I fixed it had a fat finger moment

**Comment by FreddyFish** [comment]
Please close the issue. :)
