### ISSUE TITLE
Error 400 - Inventories will not be loaded

### ISSUE THREAD

**Issue by jemaCS** [pepzwee/node-csgo-web-tradebot#118]
### Expected behavior
Should load inventories when you sign in.

### Actual behavior
Instead gives out an error.

### Steps to reproduce the behavior
Just load up the site. (csdreams.eu)

### Other
1. [Operating System]: Ubuntu 16.04
2. [Node.js version]: v6.12.0
3. [How did you start the script]: pm2 start index.js -n "Tradebot"

### Error Stack
Something went wrong.. please try again. (400)

**Comment by FreddyFish** [comment]
Seems like you do not have access to the API you are trying to access.

**Comment by jemaCS** [comment]
I have bought the API from SteamApis. I chose the steam inventory and market items endpoints.

**Comment by FreddyFish** [comment]
And you have the API key entered in your config?

**Comment by pepzwee** [comment]
Probably not enough funds on account or invalid API key used.

**Comment by jemaCS** [comment]
I have around 9€ left on my account and it's cost's 7,50€ a month. Also I have checked that I have my API key in my config multiple times, and it's still there. :D

**Comment by pepzwee** [comment]
Email me your ``config.js`` file with ``username``, ``password`` and the two secret values removed. Keep API keys and other stuff as is.

hello@pepzwee.com

**Comment by jemaCS** [comment]
Done.

**Comment by pepzwee** [comment]
Looks like old config file, download the latest files. There's ``appID`` etc.. missing.

**Comment by jemaCS** [comment]
Where do I get the latest files from? I just downloaded them today!

2017-11-09 1:29 GMT+02:00 Kristjan Kirpu <notifications@github.com>:

**Comment by jemaCS** [comment]
Where do I get the latest files from? I just downloaded them today!

**Comment by pepzwee** [comment]
Where did you download them from?

**Comment by jemaCS** [comment]
I downloaded it from github and through putty using git. I just compared the config files and they were exactly the same. But from your link, now it's updated. Is there anyway that I can change my current files without losing my changes on the site?

**Comment by pepzwee** [comment]
Depends on what you've changed and also how old your files are compared to the updated files. It's something you'll have to figure out yourself.

Usually updates are backend related so you could try copying and pasting your frontend files and see if it works.

**Comment by jemaCS** [comment]
I've basically only done changes to the index.html and bootstrapper.css files. That's frontend, right? I'm new to English development termiology. :P

**Comment by pepzwee** [comment]
Yes, that's front-end.

**Comment by jemaCS** [comment]
I did the backend changes. Nothind changed, but now I cannot log in. 
When I try to login it gives me this error: 403 Error: Check your API key is correct
I checked it multiple times and it is right. Both of them.

Thanks for the fast support btw! :D

**Comment by jemaCS** [comment]
Oh and my front-end files are around 3 months old.

**Comment by pepzwee** [comment]
Paste the contents of ``lib/inv.js``

**Comment by jemaCS** [comment]
I replaced everything, including the inv.js, but the index.html, bootstrapper.css and images. No change. 😭

**Comment by pepzwee** [comment]
Did you restart the script?

**Comment by jemaCS** [comment]
Oh damn, that's a good idea. I'll try it now!

**Comment by jemaCS** [comment]
Works now! Thanks so much! Now I just need to wait a week until my trade hold is gone!
