### ISSUE TITLE
Trade Status {}

### ISSUE THREAD

**Issue by jemaCS** [pepzwee/node-csgo-web-tradebot#121]
### Expected behavior
Upon pressing the trade button, I'd expect to get a trade offer.

### Actual behavior
But instead nothing happens.

### Steps to reproduce the behavior
Just press the trade button.

I have paid for Steamapis, I have tested both Steam Api keys for my main account and bot account, but nothing works.

**Comment by FreddyFish** [comment]
What  is your website URL?

1. Are you using the latest files form this repo?
2. Did you remember to deposit 5€/$ to the bot steam account you are using?

**Comment by jemaCS** [comment]
Yes, I have the latest files.
I haven't used anymoney on the bot account, but I have gifted it CS:GO. Is this not enough?

**Comment by jemaCS** [comment]
Also the url is csdreams.eu

**Comment by FreddyFish** [comment]
1. Login to the bot account in the browser version of steam.
2. https://steamcommunity.com/dev/apikey
3. Can you generate a steam API key here? - Remember to be logged into the bot account.

**Comment by FreddyFish** [comment]
- Also can you take a screenshot of your console log?

**Comment by jemaCS** [comment]
Where can I find this console log that you want? 
Also I did login with my bot account to get the other steam api key, but no difference.

**Comment by FreddyFish** [comment]
The other steam API key?
There is only one steam API key.

The log of the script itself.
The script should show some logs when you start it with node index.js

**Comment by jemaCS** [comment]
I start it with pm2, but here is what happens when I restart it with pm2.
![putty](https://user-images.githubusercontent.com/33499483/32989324-b08296ae-cd1c-11e7-8900-c319085a8124.JPG)

**Comment by jemaCS** [comment]
Wellp, I started it with node index.js now. I don't have the polls/bot_1.json file. Where do I get that from?
Here is the log:
![image](https://user-images.githubusercontent.com/33499483/32989389-aa136482-cd1d-11e7-974e-f42c6e4e4277.png)

**Comment by jemaCS** [comment]
Fixed it.
