### ISSUE TITLE
What this error means ? 

### ISSUE THREAD

**Issue by robesas** [pepzwee/node-csgo-web-tradebot#123]
https://i.gyazo.com/b8ba2c79b70dd0066e39a626cda47b60.png

Hello, what this error means, is it a big deal ?

**Comment by FreddyFish** [comment]
No, its fine.
Dont worry about it.

**Comment by robesas** [comment]
Thx for answer, one more question. Where is a way to withdraw skins from bot, without depositing anything in exchange ?

**Comment by robesas** [comment]
find it
