### ISSUE TITLE
Trade status {}

### ISSUE THREAD

**Issue by Diaper1** [pepzwee/node-csgo-web-tradebot#124]
### Expected behavior
Send Trade offer
### Actual behavior
Doesnt Send trade offer gives 
0|Tradebot | Error: ENOENT: no such file or directory, open './polls/bot_1.json'
0|Tradebot |     at Error (native)

### Other
1. [Operating System]: <here>
2. [Node.js version]: <here>
3. [How did you start the script]: <here>
My bot is able to trade on steam(Added 5$ have all codes correct and the steam api key correct) Getting this log error. Anyone know how to fix?

**Comment by Diaper1** [comment]
fixed

**Comment by FreddyFish** [comment]
@Rakeo - Just read the error message?

> 0|Tradebot | Error: ENOENT: no such file or directory, open './polls/bot_1.json'
