### ISSUE TITLE
Add a border-color  depending on the rarity of the item

### ISSUE THREAD

**Issue by rafaelguedes** [pepzwee/node-csgo-web-tradebot#127]
I know this is not an 'issue/bug' but since I've subscribed the SteamApis.com services, I guess its fair enough to throw it here.

What I want to do: 
- Add a border-bottom to every item with a color that represents the rarity of the item.

Is there some property in the objects returned by the Steam Apis that would allow me to implement this? If there's one, can you give some tips of how I should integrate the request in this flow with vue.js?

Thanks a lot.

**Comment by pepzwee** [comment]
Yes, you would be able to do this in ``lib/inv.js`` since you can get the rarities from the inventory data.

**Comment by rafaelguedes** [comment]
There's a property data.type that return that type of the item (Industrial, Mil-Spec, etc).
I've assigned a rgb colour depending on the type returned and was able to implement this.
