### ISSUE TITLE
Getting float of bot's new items

### ISSUE THREAD

**Issue by vladbuich** [pepzwee/node-csgo-web-tradebot#128]
Bot's float values don't update after trades. New bot's items haven't float value.
How can I fix this?

**Comment by pepzwee** [comment]
Only new items don't have a float value?

**Comment by vladbuich** [comment]
yes, when bot get new item, its float value doesn't update

**Comment by pepzwee** [comment]
Alright, I'll take a look at it soon

**Comment by reynirf** [comment]
I'm also interested in this...

**Comment by reynirf** [comment]
The reason why new items don't get float values:
When you start the server, the bot inspects and sets the float values with the ouput from on('inspectItemInfo') (/lib/bot.js)
```

self.instances[id].csgo.on('itemInspectInfo', (item) => {
            if (item) {
                self.floats[item.itemid] = {
                    defindex: item.defindex,
                    paintindex: item.paintindex,
                    rarity: item.rarity,
                    quality: item.quality,
                    paintwear: item.paintwear,
                    paintseed: item.paintseed,
                }
            }
})
```
ItemInspectInfo returns an item which has paintwear (float value, customname (name tag) etc...
https://github.com/DoctorMcKay/node-globaloffensive#inspectiteminfo

--------------

When a new item gets acquired by the bot, on('itemAcquired') gets excecuted. 
Currently, this is the code for ItemAcquired

```
self.instances[id].csgo.on('itemAcquired', (item) => {
            if (item) {
                self.floats[item.itemid] = {
                    defindex: item.defindex,
                    paintindex: item.paintindex,
                    rarity: item.rarity,
                    quality: item.quality,
                    paintwear: item.paintwear,
                    paintseed: item.paintseed,
                }
            }
})
```

The problem with this is that **itemAcquired doesn't return the paintwear** (float value), but does only return some basic information - for instance; the assetID.
https://github.com/DoctorMcKay/node-globaloffensive#itemacquired
