### ISSUE TITLE
Price of everything is showing $NaN

### ISSUE THREAD

**Issue by martijn040501** [pepzwee/node-csgo-web-tradebot#129]
Expected behavior
- Too Show the prices of the Items

Actual behavior
- Shows All too Low %Nan

Steps to reproduce the behavior
- The code to get the prices from cs:go items doens't seem to work for me. Does someone knnow how to fix this?

Error Stack

**Comment by pepzwee** [comment]
I'm guessing you didn't have "Market / Items" enabled @ SteamApis.com - if that's not the case feel free to add additional comments for future viewers.
