### ISSUE TITLE
Cannot confirm trades

### ISSUE THREAD

**Issue by Sosik1** [pepzwee/node-csgo-web-tradebot#13]
Hello,

I'm having trouble setting up this site: It seems that the bot can't verify the trades for some reason, although if the bot isn't giving any of his items it works okay.
I'm getting this output in the box:

Trade status
{}

And the second issue is that it takes lots of time to load bots inventory. Any ideas why.

Any help would be appreciated.
Thanks,
Sosik1

**Comment by FreddyFish** [comment]
Most of the time it's steam problems.
Could also be the inventories. :)

**Comment by FreddyFish** [comment]
Inventories are grabbed from here, if that API is slow it will delay the inventory loading.
https://api.steamapis.com/steam/inventory

It could also be because your PC/server is slow.

**Comment by Sosik1** [comment]
I don't know man, I was having the issue yesterday as well.
What could it be?

**Comment by Sosik1** [comment]
Okay, maybe yes, but the main thing is the trade confirm, it doesn't send trades!
You guys have this problem?
Im running it on a linux 14.04 64 bit vps

**Comment by FreddyFish** [comment]
Mine works just fine...
Had some problems, but it's mostly steam/API issues.

**Comment by Sosik1** [comment]
So, what am I doing wrong?

**Comment by FreddyFish** [comment]
Nothing. Does anything weird pop up in the console?
Also please read the read-me.

**Comment by Sosik1** [comment]
I read the readme.
Does it say anywhere in the readme that I should not ask for help?
And yes, the console says, that it sent the offer.
But I dont recieve any offers. And should it say something different than "Trade status {}" after sending a trade?

**Comment by FreddyFish** [comment]
Yeah it should say that you have 10 minutes to accept.
I was just pointing out that this script is not 100% bullet-proof working.

**Comment by Sosik1** [comment]
Yeah, I know... 
So weird says that it sends the trade, but accually doesn't.
What system did you run it on?

**Comment by xChr11s** [comment]
Maybe Post your Link so we can Check ?
Are you using the Last Version ?

**Comment by Sosik1** [comment]
http://vps380468.ovh.net/
So this is the link for my website.
Im using the latest version of this scipt downloaded today, on ubuntu 14.04 64 bit.

**Comment by pepzwee** [comment]
Could you provide the steamID64 and tradelink of your bot account. What are the specs of your VPS?

Inventory API is not slow at the moment, it's performing good.

**Comment by pepzwee** [comment]
Also, when in SSH (Console) input this command and let me know the results `ping api.steamapis.com`

**Comment by Sosik1** [comment]
Okay so the vps is good i have 2gb of ram and a few vcores probably two, so i tkink its enough.
And trade link and Steam id in a sec

**Comment by Sosik1** [comment]
Steamid: 76561197962000969
tradelink: https://steamcommunity.com/tradeoffer/new/?partner=1735241&token=7ZeJ2AC2

--- api.steamapis.com ping statistics ---
15 packets transmitted, 15 received, 0% packet loss, time 14021ms
rtt min/avg/max/mdev = 9.332/9.565/10.859/0.418 ms

**Comment by Sosik1** [comment]
Maybe its the node modules?
They werent provided so i copied from a different site script.

**Comment by pepzwee** [comment]
You're amazing. Delete the `node_modules` folder and run `npm install`

**Comment by Sosik1** [comment]
Ok let me try

**Comment by FreddyFish** [comment]
Really? Really?
Is this your first time using node?

I have said it before, and i'm going to say it again. If you can't set this up this script is not for you.

**Comment by Sosik1** [comment]
Okay its deleting.
When its done i'll try

**Comment by Sosik1** [comment]
Everyone had to start somewhere lol
