### ISSUE TITLE
Clicking sign in through steam gives a 404 Error: /auth/steam could not be found

### ISSUE THREAD

**Issue by sbendeschii** [pepzwee/node-csgo-web-tradebot#134]
### Expected behavior
When I click sign in through steam, it should take me to the steam sign in page, and then return me back to the trading site, already signed in.

### Actual behavior
When I click sign in through steam, it gives me a 404 Error saying <ip of my site>/auth/steam could not be found. In the folder containing the script files, there is no Auth or Steam directory as well. It's not included in the download.

### Steps to reproduce the behavior
Click sign in using the provided zip file on github

### Other
1. [Operating System]: <Windows 10>
2. [Node.js version]: <Latest as of 1/9/2018>(Node.js isn't causing the issue)
3. [How did you start the script]: <Uploaded the files to my vps using filezilla, just like any other website.>

### Error Stack
-bash: cd: /auth/steam: No such file or directory (Putty)

(When clicking sign in)
Not Found
The requested URL /auth/steam was not found on this server.

**Comment by pepzwee** [comment]
Disable Apache or nginx

⁣Sent from Blue ​
