### ISSUE TITLE
Site refuses connection

### ISSUE THREAD

**Issue by Trollodeboy** [pepzwee/node-csgo-web-tradebot#138]
Hello. I just tried to setup your script and I came across this problem. 4/5 times I try to connect to my site, Chrome gives me the following error: ERR_CONNECTION_REFUSED.
The 1/5 times the site does work, everything works fine expect that I can't login, because of this error.

Has anyone any idea why this happens and how I can fix it? 

Thanks.

**Comment by iDefineHD** [comment]
Uninstall apache
