### ISSUE TITLE
Right click to inspect items 

### ISSUE THREAD

**Issue by NadirRed** [pepzwee/node-csgo-web-tradebot#139]
Hello,
is it possible to add a inspect link for each item when you right click on it ?

**Comment by iDefineHD** [comment]
Yes it is possible. With a little code change. And css work. Although pepzwee isn't supporting the release now unless major bugs are found.

**Comment by FreddyFish** [comment]
Everything is possible. You just have to make it yourself. :)

**Comment by NadirRed** [comment]
thank you ^^
