### ISSUE TITLE
tooltip hidding under div

### ISSUE THREAD

**Issue by NadirRed** [pepzwee/node-csgo-web-tradebot#141]
### Expected behavior
tooltip show

### Actual behavior
tooltip hidding under these 4 divs
panel panel-default
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">
<span><span class="well well-sm"><strong>Your offer</strong></span></span>
<span class="price pull-right">
<span class="well well-sm">${{ userInventorySelectedValue.toFixed(2) }}</span>
</span>
</h3>
</div>

### Other
1. [Operating System]: <here>
2. [Node.js version]: <here>
3. [How did you start the script]: <here>

**Comment by pepzwee** [comment]
1. Could you make a screenshot?
2. Have you changed any CSS?
3. Have you changed any HTML?

**Comment by NadirRed** [comment]
i delete the div that has "Please, select items that you want to trade"
and now tooltip hide under the panel-heading div
![tooltip](https://user-images.githubusercontent.com/11279083/36095728-ad9678b0-0ff3-11e8-8aa8-1d83b772fca7.png)
Notes :
* i changed some CSS but only colors & width & heigh, didnt change any z-index value or position value
* i didnt change the HTML

**Comment by pepzwee** [comment]
The div was there for exactly that reason. Since this is not an issue with the code itself and you've modified the front-end files I will keep this issue closed.

**Comment by NadirRed** [comment]
is there a possible fix for the issue ??
please help

**Comment by pepzwee** [comment]
Add the "Select items" div back in, any other solutions are up to you.
