### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by Gooket** [pepzwee/node-csgo-web-tradebot#142]
Hi, could you help?
I need to add authorization, but I do not understand how to do this.
Thank you in advance.

**Comment by FreddyFish** [comment]
Please explain, what have you tried so far?
And what  are you doing wrong?

**Comment by Gooket** [comment]
I use Google to find documentation about the authorization through Steam, unfortunately I do not fully understand how to load inventory, and in general fully run your script.

Sorry, I'm using an interpreter. If something is not clear, write, I'll try to describe it differently.

**Comment by FreddyFish** [comment]
Just follow the tutorial made by pepzwee.. :) 
here: https://steamapis.com/projects/node-csgo-web-tradebot

**Comment by Gooket** [comment]
One more question.
After authorization, an error occurs

Cannot GET //auth/steam/return
If you delete one extra /, then the authorization is successful, could you tell me how to fix this bug?

**Comment by Gooket** [comment]
Also could you tell, is it possible to add all users who have passed authorization into the database? I need to create a balance.

**Comment by Gooket** [comment]
And the last question for today, changing the game ID will affect the overall system of the trade? For example, if I want to exchange objects DotA 2. If so, what difficulties can arise?

**Comment by FreddyFish** [comment]
1. Check your config.js file. You made a "/" at the end of the URL.
2. Yes, it's possible to add all users to a database. You just have to create it yourself.
3. Yes, it is possible to change the game to Dota 2.  - You just have to figure out how! 

No one here is going to spoonfeed you, so you will have to figure out most thing on your own. Please keep in mind, if you have 0 experience with node.js I would not advise you to run this script.

**Comment by pepzwee** [comment]
@FreddyFish covered basically everything. Thanks.
