### ISSUE TITLE
Stop accepting a specific item?

### ISSUE THREAD

**Issue by almatrass** [pepzwee/node-csgo-web-tradebot#145]
How would I stop the bot accepting a specific item? Or manually set the price of a specific item

**Comment by Vlady17** [comment]
Add unstable checker. Why did you scammed your subscriber?

**Comment by Vlady17** [comment]
This guy deposited his last money on his site and he liked, commented your video, gave you a feedback and helped as well. If you have heart, you may trade him his items back.
If you do this, I will help you with writing this function...

**Comment by Vlady17** [comment]
Someone deposited overpriced stickers on your site and you deposited this stickers on the subscriber's site to get your money back. Why just not tell him that there is a bug that need to be fixed? This stickers were your problem, but not his problem. I think you don't want to loose reputation on YouTube and make your subs to not trust you.

**Comment by almatrass** [comment]
Those skins took a price drop, checked all the sites in my history, his was the only site accepting, so he turns round and cucks me with fucking 77 battle scarred sawed offs which had been manipulated like fuck 2 days ago. Don't give off to me give off about this glitched api

**Comment by tepeumut** [comment]
inv.js
add this code : && description.market_hash_name.indexOf('NAME') === -1 in line 25
you can blocked all sticker or block sticker name

**Comment by Vlady17** [comment]
@almatrass instant karma?
