### ISSUE TITLE
Using the unstable value

### ISSUE THREAD

**Issue by almatrass** [pepzwee/node-csgo-web-tradebot#146]
Hi, apologies for opening another issue as I opened one two days ago, but does anyone know how to use the unstable value from the response? Thanks

**Comment by iDefineHD** [comment]
Why would you want to use the unstable prices? That wouldnt make any sense.

**Comment by pepzwee** [comment]
He wants to use these values from the non-compact response. Not actual unstable prices.
`"unstable_reason": false, "unstable": false`
