### ISSUE TITLE
still - literally impossible to login into steam 

### ISSUE THREAD

**Issue by coooool123** [pepzwee/node-csgo-web-tradebot#148]
https://imgur.com/a/PDLrC

Whenever I try to login into steam this is the error I get, halp.

**Comment by pepzwee** [comment]
You're running Nginx and that conflicts with this Node script which also wants to run on port 80.
Either turn off Nginx or set it up as a reverse proxy.

**Comment by coooool123** [comment]
Oh sorry for posting on that old lock thread, didn't see your comments here - How exactly do I do that? Which would you prefer for me to do close it or create a reverse proxy?

**Comment by pepzwee** [comment]
I don't have a preference. You decide.

**Comment by coooool123** [comment]
Which is the hardest?

**Comment by iDefineHD** [comment]
Use https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04 if you choose reverse proxy or straight up juat run the node app.

**Comment by pepzwee** [comment]
I made this gist a year ago on how csg0.trade was reverse proxied.
https://gist.github.com/pepzwee/2e1f4e0f7f9ec29c7dfca8fabd48dfa5

**Comment by iDefineHD** [comment]
Yeah or use that. Forgot about that. :kissing_heart:

**Comment by coooool123** [comment]
Will it affect my SSL that I plan on putting in within the cfg?

**Comment by coooool123** [comment]
sudo update-rc.d -f nginx disable
Would this work? Dont want to be hasty

**Comment by pepzwee** [comment]
There's three ways you can add SSL to this script.

1. Nginx reverse proxy with SSL
2. Cloudflare proxy with SSL
3. Add it to the script itself, which is slightly harder than the options above

If you don't have any nginx websites online and you don't need it, you can just disable it correct.

**Comment by coooool123** [comment]
Whats the command to open up the nginx config so I can change it?

**Comment by coooool123** [comment]
Anything?

**Comment by coooool123** [comment]
I have a new error now “Apache/2.4.18 (Ubuntu) Server at [my domain] Port 80” I deleted nginx and this is what happened

**Comment by iDefineHD** [comment]
You also have apache installed.

**Comment by coooool123** [comment]
What do you mean?

**Comment by coooool123** [comment]
I typed “httpd -k uninstall“ and it says that there was no httpd found

**Comment by coooool123** [comment]
I just went on file zilla and just deleted the files manually and I still get the same error, can you guys help me?

**Comment by pepzwee** [comment]
This is all you need to follow - https://steamapis.com/projects/node-csgo-web-tradebot/

**Comment by coooool123** [comment]
![52bd171c6d93eda62dfd68a26c1f1c75](https://user-images.githubusercontent.com/32992953/38399815-a95a5032-391a-11e8-8630-e5fb2ca82380.png)

**Comment by coooool123** [comment]
https://gyazo.com/8c02103bae5d46a601a81c120f0e4811 Does this mean I have these things installed? Because i've typed in the commands to remove them but I'm assuming they aren't working

**Comment by pepzwee** [comment]
You are not following the guide properly. Where does the guide tell you to use ``update-rc.d``? That disables Apache from automatically starting on boot, it does not disable it while it's running.

``sudo systemctl stop apache2``

**Comment by coooool123** [comment]
those commands literally do nothing i've typed them in so many times and got 0 back from typing them in

**Comment by pepzwee** [comment]
Not all commands return something when you execute them.

**Comment by coooool123** [comment]
But it still does nothing and I still get redirected to the same 404 error page

**Comment by coooool123** [comment]
???

**Comment by coooool123** [comment]
I've fixed the issue - All I had to do was just delete the droplet and create a new one lol
