### ISSUE TITLE
Steam Login not redirecting back to the sites

### ISSUE THREAD

**Issue by coooool123** [pepzwee/node-csgo-web-tradebot#149]
### Expected behavior
A successful login from hitting the login button and being redirected to the site as usual
### Actual behavior
Once you hit the button it won't redirect you back to the page and won't login even though you have hit the login  button (login button > sign in with credentials > page doesn't redirect back to the site instead it just stays on the login page after signing into it and doesn't redirect you to the previous pages)
### Steps to reproduce the behavior
Hit the login button and the actual behavior listed above will happen
### Other
1. [Operating System]: Ubuntu 16.04.4 x64
2. [Node.js version]: whichever is listed on the steamapiskey sites
3. [How did you start the script]: via putty + digital ocean

**Comment by coooool123** [comment]
I opened up the console and had this message when trying to login "The SSL certificate used to load resources from https://steamcommunity-a.akamaihd.net will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information."

**Comment by iDefineHD** [comment]
All symantic certs are not being trusted by browsers as they were bought out. Therefore the are not a "trusted" certificate authority.

**Comment by pepzwee** [comment]
You need to update ``passport-steam``, which can be done like so ``npm i passport-steam`` inside the script directory.

**Comment by coooool123** [comment]
I did that and now the error isn't showing up anymore in console so thanks but I still can't get redirected back to the site

**Comment by coooool123** [comment]
To be able to login do I need to purchase/install the steamapiskey key first?

**Comment by pepzwee** [comment]
No, to be able to login your config file needs to have proper URL's and Steam API key. SteamApis.com key is required to load inventories and prices.

**Comment by coooool123** [comment]
![b7ef29a4cd625a69d030344086256a5d](https://user-images.githubusercontent.com/32992953/38418195-735133ee-3969-11e8-9675-a0bc03a0226a.png)

**Comment by coooool123** [comment]
The error is still persistent please help

**Comment by Vlady17** [comment]
fix steam-passport library https://github.com/liamcurry/passport-steam/pull/74

**Comment by coooool123** [comment]
Thanks i'll try it out vlad

**Comment by coooool123** [comment]
@Vlady17 It still doesn't work for me!!I went to ``root/.npm/passport-steam`` and typed in the ``npm i passport-steam`` command and still nothing :(
