### ISSUE TITLE
Allow specific php files ?

### ISSUE THREAD

**Issue by xChr11s** [pepzwee/node-csgo-web-tradebot#15]
Hey guys !
Currently expecting some issues with a file. I've created a php file for example named test.php.
If I try to open it on site, I'm getting "Cannot GET /test.php"
I think I have to edit something in Index.js, but I can't get it to work actually.
Pretty new to vuejs :/
Would be cool if someone could help me with this !

Thanks in advance !

**Comment by FreddyFish** [comment]
What do you mean, why would you want to create a /test.php file?
The script is not even running on php.

**Comment by xChr11s** [comment]
The php file shows the bot online status. Yes I know but shouldn't it be possible ?
Otherwise do you know a way to get the online status of a steam account in js ?

**Comment by pepzwee** [comment]
Just use Steam's API, it  provides the `personastate` of a user. https://developer.valvesoftware.com/wiki/Steam_Web_API#GetPlayerSummaries_.28v0002.29

**Comment by pepzwee** [comment]
A module installed with this script can already give you the data that you need.
https://github.com/DoctorMcKay/node-steamcommunity/wiki/CSteamUser

**Comment by pepzwee** [comment]
Also, you can't run php scripts with node afaik. Use a reverse proxy.
