### ISSUE TITLE
"The SSL certificate used to load resources from https://steamcommunity-a.akamaihd.net will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information." Error

### ISSUE THREAD

**Issue by coooool123** [pepzwee/node-csgo-web-tradebot#151]
I have YET ANOTHER new issue which is still not redirecting me back to the site but now I get this error message when I try to login now: "The SSL certificate used to load resources from https://steamcommunity-a.akamaihd.net will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information." Which is in my console whenever I try to login and the page won't redirecet like it should.
![62ea645deb899a2fb5cca4daabc2caa8](https://user-images.githubusercontent.com/32992953/38451415-95e31d98-39fd-11e8-94cd-4783f4900362.png)

**Comment by pepzwee** [comment]
Unrelated to this script.
