### ISSUE TITLE
Can't redirect to steam

### ISSUE THREAD

**Issue by coooool123** [pepzwee/node-csgo-web-tradebot#152]
### Expected behavior
Redirect to site from login page
### Actual behavior
Once you hti the login button you get redirected to steams login page then after you sign in and ect. the page won't redirect you back to your site instead it just refreshes and asks you to login again
### Steps to reproduce the behavior
Click the login button and trying to sign in 
### Other
1. [Operating System]: ubuntu 16.04
2. [Node.js version]: whatever is listed on steamapis project pages
3. [How did you start the script]: wut

### Error Stack
https://gyazo.com/b15b4faa1d33be69f25ea7da1daa701b

**Comment by coooool123** [comment]
update: when I hit sign in it just redirects me too this "https://steamcommunity.com/openid/login"

**Comment by iDefineHD** [comment]
We have done all we can to help i suggest giving up if you can't get this working. Spamming new and old threads doesn't help your case either. Even with me not replying. I am getting spammed by you. Which ia annoying.

**Comment by iDefineHD** [comment]
And thats probably a config error.

**Comment by coooool123** [comment]
Why would I just give up when you guys can help me, you know this stuff better than I do and you guys probably do know how to fix it I don't see how it's my fault for following your guide exactly and getting an error output of doing so, not fair at all if I can't even recieve help. You guys give me vague answers and not descriptive solutions for a new commer like myself, all i'm asking for is help..

What would be wrong in the config that would cause this?

**Comment by iDefineHD** [comment]
It's not that, i only slightly, but the creator of the script has given sufficient info on how his script runs and the errors you have been getting, fair enough the auth had been f*cked up cause of steams https protocol all of a sudden, but once help was asked it was given. every other issue has still been left open if you actually look at the tab instead of keep creating new ones. You have google also to try and learn and understand like we all have, i am a nob myself, but can get around code and systems. Just saying. Don't have a go at me for pointing out the obvious.

**Comment by coooool123** [comment]
I don't see anything on google so I came here - the source of all this. You still haven't answered my question btw

**Comment by pepzwee** [comment]
> This is a quickly coded website for people who want to see how these kind of websites work. Before you decide to use this script be aware, that this script, may have bugs. I also suggest looking through the code to see how it works, and if you spot an error make a pull request.

> The following script is not meant for beginners. It's strongly advised to learn how the code works before using it.

> Keep in mind this project is free and open-source. Don't expect support to be good and fast.

I just cloned the repository, set it in 10 minutes without any issues what-so-ever. Obviously you're doing something wrong on your own end.

- Cloned the repository
- Installed dependencies
- Edited config file
- Manually created polls/bot_1.json file
- Added Cloudflare and enabled SSL
- Ran the script

Here's the config I used https://gist.github.com/pepzwee/d67751d5f66f599814e93f750d2ca988

**Comment by coooool123** [comment]
I got it working! If anyone else is having this issue all you need to do is change your steam API key from its regular domain (without the http, ect.) and when typing in the domain api key again it should be like this: "https://<your domain>" instead of it just being "<your domain>" then you'll be given a new api code to apply to your config - It worked for me, I hope it works for you.

**Comment by pepzwee** [comment]
Glad you sorted it out.
