### ISSUE TITLE
Trade status Timeout after "Confirming sent offer" & possibility of adding Too Low Items

### ISSUE THREAD

**Issue by xChr11s** [pepzwee/node-csgo-web-tradebot#16]
Hey, while trying a bit around I figured out this:
https://i.gyazo.com/8433fe8b9c7c9ffa5a293490721746ad.png

It took a long time after "Confirming sent offer" and showed just "{ "code": "ETIMEDOUT", "connect": true }"
Any Idea how to solve this ?

btw. It is possible to Add "Too Low" Items if you remove the disabled="disabled" with developer tools, but this was in the end already mentioned here https://github.com/pepzwee/node-csgo-web-tradebot/issues/9

Kind regards

**Comment by pepzwee** [comment]
That error is too broad, can u get more info?
About issue #9 - I don't really have the time to do a fix for it. There's a reason this is open source.

**Comment by xChr11s** [comment]
Looks like its only happening if I add an Item which is tagged with "Too Low", but I was able to get one trade with an tagged item, the others all got this error. Tried around 4 or 5 times..
No problems with normal Items..

If I got time I will try to check issue 9 out .. maybe I can fix it.

**Comment by fortza** [comment]
yes if you remove the disabled="disabled" with developer tools , u pass the restriction TO LOW :D and exchange low items for good items

**Comment by fortza** [comment]
this help ?

		            if(anyDuplicates || badTrade || blackListedItem || maxLimitReached || minLimitReached || Unstable) {
		            	console.log(colors.red.bold("Bad trade."));
		            	console.log(colors.red.bold("Duplicates: " + anyDuplicates));
		            	console.log(colors.red.bold("Fake items: " + badTrade));
		            	console.log(colors.red.bold("Black listed items: " + blackListedItem));
		            	console.log(colors.red.bold("Too expensive item found: " + maxLimitReached));
		            	console.log(colors.red.bold("Too cheap item found: " + minLimitReached));
                        console.log(colors.red.bold("Unstable item found: " + Unstable));
		                socket.emit('trade_error',{});
                                console.log("Kappa 2");
		            } else {
		            	//If there are two or more bots
		                if(numberOfBots > 1) {
		                    //Check if trade is valid
							console.log("----> New Trade Offer!");
		                    console.log("# Bot Value: " + botCurrentValue/100);
		                    console.log("# User Value: " + userCurrentValue/100);
		                    console.log("# Profit ($): " + (userCurrentValue/100 - botCurrentValue/100));
		                    console.log("# Profit (%): " + ((userCurrentValue - botCurrentValue) / botCurrentValue) * 100);

**Comment by fortza** [comment]
for (var key in data.give) {
                            if (!data.give.hasOwnProperty(key)) continue;
                            var obj = data.give[key];
                            obj.forEach(function(element) {
                                var found = false;
	                        	var type = getItemType(element.name);
	                            myInv.forEach(function(item){
	                                if(element.id == item.assetid && element.name == item.market_hash_name) {
	                                    found = true;
	                                }
	                            });
	                            if(!found) {
	                                badTrade = true;
	                            }
                            }, this);
                        }
                        var IDs = [];
                        data.recieve.forEach(function(item){
                            if(IDs.indexOf(item.id) > -1) {
                                anyDuplicates = true;
                            }
                            IDs.push(item.id);
                        });
                        for (var key in data.give) {
                            if (!data.give.hasOwnProperty(key)) continue;
                            var obj = data.give[key];
                            obj.forEach(function(item) {
                                if(IDs.indexOf(item.id) > -1) {
	                                anyDuplicates = true;
	                            }
	                            IDs.push(item.id);
                            }, this);
                        }

**Comment by fortza** [comment]
if(!Unstable) {
                        //Getting user items value and checking duplicate item assetID
                        data.recieve.forEach(function(element) {
                            var found = false;
                            var type = getItemType(element.name);
                            inv.forEach(function(item){
                                if(element.id == item.assetid && element.name == item.market_hash_name) {
                                    if(prices.value[element.name].price * newRates[type].theirs/100 > rates.max) {
                                        maxLimitReached = true;
                                    }
                                    if(prices.value[element.name].price < rates.min) {
                                        minLimitReached = true;
                                    }
                                    userCurrentValue += prices.value[element.name].price * newRates[type].theirs;
                                    found = true;
                                }
                            });
                            if(!found) {
                                badTrade = true;
                            }
                        }, this);

                        for (var key in data.give) {
                            if (!data.give.hasOwnProperty(key)) continue;
                            var obj = data.give[key];
                            obj.forEach(function(element) {
                                var found = false;
	                        	var type = getItemType(element.name);
	                            myInv.forEach(function(item){
	                                if(element.id == item.assetid && element.name == item.market_hash_name) {
	                                    found = true;
	                                }
	                            });
	                            if(!found) {
	                                badTrade = true;
	                            }
                            }, this);
                        }
                        var IDs = [];
                        data.recieve.forEach(function(item){
                            if(IDs.indexOf(item.id) > -1) {
                                anyDuplicates = true;
                            }
                            IDs.push(item.id);
                        });
                        for (var key in data.give) {
                            if (!data.give.hasOwnProperty(key)) continue;
                            var obj = data.give[key];
                            obj.forEach(function(item) {
                                if(IDs.indexOf(item.id) > -1) {
	                                anyDuplicates = true;
	                            }
	                            IDs.push(item.id);
                            }, this);
                        }

**Comment by fortza** [comment]
**replace with this** 

Trade.prototype.getPrice = function(name, rateType, itemType) {
     if (this.prices[name] < 1)
	 {return -1;}
	 else
    {return this.prices[name] * config.rates[rateType][itemType.name] || 0;}
}

    **replace with this** 

if(obj.user.length) {
        self.getInventory(obj.steamID64, '730', '2', (err, data) => {
            if( ! err) {
                let userInventory = data;
                for(let i in userInventory) {
                    let item = userInventory[i];
					 let flag = self.getPrice(item.data.market_hash_name, 'user', item.item_type);
                    if(obj.user.indexOf(item.assetid) !== -1 && flag!=-1) {
                        userCount = userCount + 1;
                        userValue += self.getPrice(item.data.market_hash_name, 'user', item.item_type);
                    }
                }

 ALL THIS REPLACE IN /lib/index.js

**Comment by pepzwee** [comment]
Don't post unformatted code in issue thread. Any "fixes" should be added as pull requests so that people can review them.

**Comment by fortza** [comment]
oke 1 sec

**Comment by fortza** [comment]
check it pepzwee is correct fix ;)

**Comment by fortza** [comment]
The pull request that i open fix this and all open problems.

**Comment by pepzwee** [comment]
Timed out is not an issue with this package. Seems to occur when Steam has issues. Feel free to let me know if I'm wrong.
