### ISSUE TITLE
Trade status {}

### ISSUE THREAD

**Issue by Suchismit4** [pepzwee/node-csgo-web-tradebot#161]
It gives me the order of 
` Trade status
{}
` when trynna send a trade offer

**Comment by iDefineHD** [comment]
Do you have anymore to add to this? Error trace etc or? Could be several things. P.s the project is not supported by the original creator.

**Comment by iDefineHD** [comment]
No reply has been given within 2 days, I will lock this for now. Create a new issue if needed.
