### ISSUE TITLE
Again! Error (not the same) 

### ISSUE THREAD

**Issue by Suchismit4** [pepzwee/node-csgo-web-tradebot#164]
`Sorry!
An error was encountered while processing your request:

Invalid return protocol`

`'use strict'

module.exports = {
    appID: 252490,
    contextID: 2, 
    bots: {
        bot_1: {
           
        },
    },
    steamApiKey: '', 
    SteamApisKey: '',
    domain: 'localhost:3000',
    SteamApisCompactValue: 'safe_ts.last_30d', // Use safe price calculated from 30 days of data, more info: https://steamapis.com/developers (Market Items - Optional Query Parameters "compact_value")
    site: {
        header: 'CSG0.Trade', // Name/header/title of website. Prefix for  <title></title> (For more: /index.html line: 9) 
        steamGroup: '#',
        copyrights: 'Copyright © csg0.trade 2017',  // Copyright text
    },
    website: 'localhost',    // Website URL, follow the example (do not add / at the end)
    websitePort: 3000,    // Website PORT, don't change it unless you're using a reverse proxy
    tradeMessage: 'Trade offer from csg0.trade | If you did not request this offer or the offer looks invalid please decline.', // Quite obvious
    rates: {
        ignoreItemsBelow: 0.05, // Ignore items below this price (price * rate < ignoreItemsBelow) - shows (Too Low) for user
        trashPriceBelow: 0.2,   // Items below this price are considered trash, the trash rate modifier will be applied
        // Items
        user: {
            key: 1,
            knife: 0.95,
            rare_skin: 0.95,
            weapon: 0.9,
            misc: 0.85,
            trash: 0.7,
        },
        bot: {
            key: 1.05,
            knife: 1,
            rare_skin: 1,
            weapon: 0.95,
            misc: 0.9,
            trash: 0.8,
        },
    },
}

It is only happening for localhost
`

**Comment by pepzwee** [comment]
https://github.com/pepzwee/node-csgo-web-tradebot/blob/master/config.js#L26

Missing `http://`, please follow config instructions.
