### ISSUE TITLE
This is weird. [UNKNOWN ERR]

### ISSUE THREAD

**Issue by Suchismit4** [pepzwee/node-csgo-web-tradebot#169]
So, all previous issues were fixed.

But, idk whats this

ERR:
`
Uncaught TypeError: Cannot read property 'market_hash_name' of undefined
    at n.<anonymous> (app.js:306)
    at n.emit (index.js:83)
    at n.onevent (index.js:83)
    at n.onpacket (index.js:83)
    at n.<anonymous> (index.js:83)
    at n.emit (index.js:83)
    at n.ondecoded (index.js:83)
    at a.<anonymous> (index.js:83)
    at a.n.emit (index.js:83)
    at a.add (index.js:83)
`

Explanation:
So i added my own main.js before app.js, because i wanted to add a roulette system, and since that its causing this, when i remove that main.js.. it works fine.

Heres the sequence of how i added the js files
`
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
   <script src="/static/js/main.js"></script>
   
   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.slim.js" integrity="sha256-Dul4c09cdrWKXVtallPxF558lwxMwCC8dXJdZ0PVW54=" crossorigin="anonymous"></script>
   
   <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-90308432-1', 'auto');
      ga('send', 'pageview');
   </script>
   
   <script src="/static/js/app.js"></script>
`

APP.JS is same as it is

Here's the main.js
`
$(function(){
	var users = [],
	shuffled = [],
	loadout = $("#loadout"),
	insert_times = 30,
	duration_time = 10000;
	$("#roll").click(function(){
		users = [];
		var lines = $('textarea').val().split('\n');
		if(lines.length < 2){
			$("#msgbox").slideToggle(100);
			setTimeout(function() {
				  $("#msgbox").slideToggle(100);
			}, 3000);
			return false;
		}
		for(var i = 0;i < lines.length;i++){
			if(lines[i].length > 0){
				users.push(lines[i]);
			}
		}
		$("#roll").attr("disabled",true);
		var scrollsize = 0,
		diff = 0;
		$(loadout).html("");
		$("#log").html("");
		loadout.css("left","100%");
		if(users.length < 10){
			insert_times = 20;
			duration_time = 5000;
		}else{
			insert_times = 10;
			duration_time = 10000;
		}
		for(var times = 0; times < insert_times;times++){
			shuffled = users;
			shuffled.shuffle();
			for(var i = 0;i < users.length;i++){
				loadout.append('<td><div class="roller"><div>'+shuffled[i]+'</div></div></td>');
				scrollsize = scrollsize + 192;
			}
		}
		
		
		diff = Math.round(scrollsize /2);
		diff = randomEx(diff - 300,diff + 300);
		$( "#loadout" ).animate({
			left: "-="+diff
		},  duration_time, function() {
			$("#roll").attr("disabled",false);
			$('#loadout').children('td').each(function () {
				var center = window.innerWidth / 2;
				if($(this).offset().left < center && $(this).offset().left + 185 > center){
					var text = $(this).children().text();
					$("#log").append("THE WINNER IS<br/> <span class=\"badge\">"+text+"</span>");
					
				}
				
			});
		});
	});
	Array.prototype.shuffle = function(){
		var counter = this.length, temp, index;
		while (counter > 0) {
			index = (Math.random() * counter--) | 0;
			temp = this[counter];
			this[counter] = this[index];
			this[index] = temp;
		}
	}
	function randomEx(min,max)
	{
		return Math.floor(Math.random()*(max-min+1)+min);
	}
});
`

**Comment by Suchismit4** [comment]
Guys, can you please help me in this condition
Really in need of some help.. @pepzwee @iDefineHD :(

**Comment by iDefineHD** [comment]
> 
> 
> Guys, can you please help me in this condition
> Really in need of some help.. @pepzwee @iDefineHD :(

We do not help with regards to 3rd party scripts etc being used. As you had said it's working fine without the added script, I am closing the Issue.

**Comment by Suchismit4** [comment]
pepzwee would have suggested me a fix... thanks for your time.. you are not worth it for this resource.

**Comment by iDefineHD** [comment]
You are running a 3rd party script. Nothing to do with the project. How am I to respond. You also stated that it works fine without the modified code. You added. Therefore neither I or Pepz are obliged to help on the matter. Dont attack me for it.

**Comment by Suchismit4** [comment]
Its not that matter. sorry for me raging, but atleast you coudl have mentioned whats the err on the script... atleast that would have helped me  ,

**Comment by Suchismit4** [comment]
Can you do that for me?

**Comment by FreddyFish** [comment]
No we can't. This project is open source, no one here is going to spoon feed you. If you have no idea what's wrong, you should probably not run this, or figure out what's wrong yourself. The worst part is that you expect us to help you, even though you are not running the official code. No one here will help you when you have that attitude of yours. Issue request should be made when there is something wrong with the code of the repo. Nothing is wrong, and it's working flawlessly. Come back when you have an issue and are running the OFFICIAL source.  Have a nice evening.
