### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by cenoura008** [pepzwee/node-csgo-web-tradebot#171]
### Other
1. [Operating System]: Ubuntu 16.04 srv
2. [Node.js version]: 10

When I run npm install I'm getting this:
root@csgoprice:~/tradebot# npm install

> protobufjs@6.8.8 postinstall /root/tradebot/node_modules/protobufjs
> node scripts/postinstall

module.js:550
    throw err;
    ^

Error: Cannot find module '/root/tradebot/node_modules/protobufjs/scripts/postinstall'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm WARN tradebot@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! protobufjs@6.8.8 postinstall: `node scripts/postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protobufjs@6.8.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-27T10_42_54_291Z-debug.log

**Comment by iDefineHD** [comment]
what version of node are you running?

**Comment by cenoura008** [comment]
I used the 8 instead the 6 because it's the newest version --> curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh

**Comment by iDefineHD** [comment]
> 
> 
> I used the 8 instead the 6 because it's the newest version --> curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh

Infact, the latest release is 12 for LTS and 13 for up to date within node. Could you try [https://tecadmin.net/install-latest-nodejs-npm-on-ubuntu/](url) And then get back to me, as some packages may require a later node version.

**Comment by cenoura008** [comment]
> > I used the 8 instead the 6 because it's the newest version --> curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh
> 
> Infact, the latest release is 12 for LTS and 13 for up to date within node. Could you try [https://tecadmin.net/install-latest-nodejs-npm-on-ubuntu/](url) And then get back to me, as some packages may require a later node version.

I'm still getting the error after doing doing this!

**Comment by iDefineHD** [comment]
This could be several things. Could you supply the log it generates? Have you tried running sudo.

**Comment by cenoura008** [comment]
Here you have the log file
[2020-01-28T08_35_24_218Z-debug.log](https://github.com/pepzwee/node-csgo-web-tradebot/files/4122266/2020-01-28T08_35_24_218Z-debug.log)
