### ISSUE TITLE
Error : Trade Status {}

### ISSUE THREAD

**Issue by cenoura008** [pepzwee/node-csgo-web-tradebot#173]
### Other
1. [Operating System]: ubuntu 16.04 SRV
2. [Node.js version]: 13.7.0

### Error Stack
I'm getting the error: Trade Status {} when I press the button "TRADE".
![image (1)](https://user-images.githubusercontent.com/33322215/73929484-25f0e680-48d5-11ea-946d-21d183b20299.png)

**Comment by iDefineHD** [comment]
Look at past closed issues. Should help you fix.

**Comment by iDefineHD** [comment]
Did you sort this issue? As you have not replied in 3 days I am closing this for now.
