### ISSUE TITLE
Error when loading inventory.

### ISSUE THREAD

**Issue by ItzSimonDK** [pepzwee/node-csgo-web-tradebot#19]
Error when loading bot inventory + users inventory: **Something went wrong.. please try again! (401)**

And things you could add if u could: Inspect + Stickers. 👍 

Good work with the node trade bot.

**Comment by pepzwee** [comment]
You need to provide a SteamApis.com API key in the config file.

**Comment by ItzSimonDK** [comment]
I've tried that :)

**Comment by ItzSimonDK** [comment]
I saw another site using your node bot, also was down. But it's back up now again.

**Comment by ItzSimonDK** [comment]
By the same error.

**Comment by pepzwee** [comment]
Send me an email with your SteamApis.com key and I'll investigate.
hello@pepzwee.com

**Comment by ItzSimonDK** [comment]
I only need the Market -> Items Right?

**Comment by ItzSimonDK** [comment]
Got it to work :) By enabling some more stuff :)

**Comment by ItzSimonDK** [comment]
But i think it's a bit overpriced :/

**Comment by pepzwee** [comment]
Compared to other providers, it's actually cheaper thank you think. I'm glad you got it working.

**Comment by tuz1k** [comment]
i enabled endpoint however when i press trade it gives error 
Trade status
Could not get a price for item(s). Trade has been cancelled.

**Comment by FreddyFish** [comment]
If prices are loaded correctly, and is viewable on your site. 
Then.. It's in your config under "ignoreItemsBelow: 0.05"

If bot is having items under 0.05 you will be getting this error when trying to trade these items.
