### ISSUE TITLE
How to install Ubuntu 14.04 x64

### ISSUE THREAD

**Issue by tbl07** [pepzwee/node-csgo-web-tradebot#22]
I dont see anythink installation guide ? anyone help ?

**Comment by FreddyFish** [comment]
I do not recommend using this script, if you have 0 knowledge in nodeJS.

**Comment by tbl07** [comment]
I am the Python director and i know this is simple guide if you wanna i little tell you
`sudo apt-get update
sudo apt-get install -y curl libcurl3 libcurl3-dev
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install -y build-essential
npm i -g forever
forever start index.js`
?

**Comment by pepzwee** [comment]
```bash
sudo apt-get update 
sudo apt-get install -y curl libcurl3 libcurl3-dev 
curl -sL https://deb.nodesource.com/setup_6.x | sudo bash - 
sudo apt-get install -y nodejs 
sudo apt-get install -y build-essential 
npm i -g forever 
forever start index.js
```

Would work yes

**Comment by tbl07** [comment]
but folder doesnt work steam/auth not found the server i upload the server folder /var/www

**Comment by pepzwee** [comment]
1. That means u wrongly configured the script.
2. `steam/auth` is an endpoint, not a folder
3. `/var/www` doesn't matter, it's a node script, it can run anywhere
4. This script is not meant for people who don't know what they're doing

**Comment by tbl07** [comment]
I know it's not enough for me but i try and learn i want to little help. Just give me lead ?

**Comment by tbl07** [comment]
We are the developer ,we learn as we share i believe this.
