### ISSUE TITLE
session-file-store

### ISSUE THREAD

**Issue by fortza** [pepzwee/node-csgo-web-tradebot#26]
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/nsdfsdfsdfsdfsdfsdfwefwefw.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/nsdfsdfsdfsdfsdfsdfwefwefw.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/nsdfsdfsdfsdfsdfsdfwefwefw.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/nsdfsdfsdfsdfsdfsdfwefwefw.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/nsdfsdfsdfsdfsdfsdfwefwefw.json'

**Comment by pepzwee** [comment]
Safe to ignore it.

**Comment by fortza** [comment]
but server is loading high because of this.

**Comment by pepzwee** [comment]
https://github.com/valery-barysok/session-file-store/issues/41
