### ISSUE TITLE
User could not sign in the site through Steam

### ISSUE THREAD

**Issue by waynechong1995** [pepzwee/node-csgo-web-tradebot#29]
Hi everyone.

The thing i had configured the script correctly(Paid steamapis key, Web api key and bots), The website is now able to fetch bot inventories perfectly. However as a user to test the trade the login part doesn't work!

I had limited knowledge on debugging through the terminal, however I had personally solved some problems regarding the missing directory of polls/bot_1.js, bot credentials and etc.

I hope anyone can provide insights on whats really going on.

### Other
1. Operating System:  AWS Ubuntu 14.04.5 LTS
2. Node.js version: V6.10.2

**Comment by FreddyFish** [comment]
We need some more information.
What happends when you click the login through steam button? Do you get any errors in the console etc.

**Comment by pepzwee** [comment]
Send me your ``config.js`` file contents by email, remove your ``username`` and ``password`` values from there. **Keep everything else as it is.**

**Comment by pepzwee** [comment]
```js
    // Domain name only, follow the example (no http:// & no www & no /)
    domain: 'm4skins',
    // Website URL, follow the example (do not add / at the end)
    website: 'http://m4skins',
```
You forgot to add ``.com`` to the end of them.

**Comment by waynechong1995** [comment]
@pepzwee  Thanks! It worked. 
![image](https://cloud.githubusercontent.com/assets/26628876/24864570/2b3c1086-1e37-11e7-8a64-dc3ac7d892e2.png)

**Comment by FreddyFish** [comment]
Great! Have fun! 👍
