### ISSUE TITLE
Some Ideas!

### ISSUE THREAD

**Issue by kotik1998** [pepzwee/node-csgo-web-tradebot#3]
Here are some ideas for adding to the bot.
 -add item that you can block: example knife ( due to maket controling the item can be overpriced), cases...
 -add item filter such as no sticker, souvenirs, graffiti ....
 -add when you hover over the bot item ill appear float value skin rarity etc..
 
if i have more ideas that you would like to implement il Edit this thread.

**Comment by kotik1998** [comment]
-add if we put our csgowebsite name on our profile name we get +3% ex:
  Vik^^ csg0.trade

**Comment by kotik1998** [comment]
-add funcion between swirtching auto-login (no steam guard need to type) or manual if the user want it so.

**Comment by pepzwee** [comment]
> add funcion between swirtching auto-login (no steam guard need to type) or manual if the user want it so

If you don't provide a valid `twoFactorCode` string then it will ask the steam guard code, otherwise it doesn't.

**Comment by kotik1998** [comment]
can't we add the shared and identity secrets and it will automatically login?

**Comment by pepzwee** [comment]
It **does** login automatically

**Comment by kotik1998** [comment]
i meant login automatically with the steam guard code where you dont need to type anything on the console.

**Comment by pepzwee** [comment]
And that's what I'm talking about as well.

`twoFactorCode` = `shared_secret`
`identitySecret` = `identity_secret`

The script **does** automatically log in the bots if you enter correct values.

**Comment by kotik1998** [comment]
oh i got it thanks!

**Comment by csgotester** [comment]
Any back-doors in this?

**Comment by FreddyFish** [comment]
Why are you posting this here?
The code is open source, go look for yourself..

**Comment by pepzwee** [comment]
@csgotester 

1. Read the code idiot, there's a reason it's on Github
2. Read the code idiot, `package.json`, `npm install`.

**Comment by FreddyFish** [comment]
Yeah.. If you don't know how to set this up, you should probably not run it.
