### ISSUE TITLE
Error: ENOENT

### ISSUE THREAD

**Issue by minecraftinventz** [pepzwee/node-csgo-web-tradebot#34]
### Expected behavior

Site works as normal

### Actual behavior

Site won't load

### Steps to reproduce the behavior

Set up site as normal

### Other
1. [Operating System]: Win 10
2. [Node.js version]: 7.7.3
3. [How did you start the script]: node index.js

### Error Stack

(node:7192) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
fs.js:92
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\Lewis\Downloads\node-csgo-web-tradebot-master\polls\bot_1.json'

**Comment by jhilgenberg** [comment]
> Error: ENOENT: no such file or directory, open 'C:\Users\Lewis\Downloads\node-csgo-web-tradebot-master\polls\bot_1.json'

create the file manually with this content:
{}

This should fix your problem.
