### ISSUE TITLE
Steam Authentication not working?

### ISSUE THREAD

**Issue by MrMedusa** [pepzwee/node-csgo-web-tradebot#35]
### Expected behavior
Get redirected to steam login page

### Actual behavior
Redirects to auth/steam, but that's not an actual directory

### Steps to reproduce the behavior
No clue how to reproduce this, but it happens on all of my devices.

### Other
1. [Operating System]: OSX 10.12.4
2. [Node.js version]: Latest Version
3. [How did you start the script]: node index.js

### Error Stack
No error stack

**Comment by pepzwee** [comment]
You either configured it wrong or you're running apache/nginx alongside it.

**Comment by MrMedusa** [comment]
I'm using apache as webserver yea. Is that wrong?

**Comment by xChr11s** [comment]
Yes, you dont need to run apache. Stop the Apache Service ! You have to run index.js with node and everthing should work.
