### ISSUE TITLE
Starting issue

### ISSUE THREAD

**Issue by zippy4** [pepzwee/node-csgo-web-tradebot#39]
When starting the bot with all information added to the config.js I receive this error message:
`Bot (bot_1) has been logged-in.
[!] All bots online.
[!] Website server is online.
[!] Socket server is online.
Steam Guard App Code: QKJ99
fs.js:101
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\Desktop\node-csgo-web-tradebot-master\polls\bot_1.json'
    at Error (native)`
I only get this error when I enter my bot's details.

**Comment by pepzwee** [comment]
https://github.com/pepzwee/node-csgo-web-tradebot/issues/34
