### ISSUE TITLE
Error 400, when loading Steam Inventory, in browser all OK.

### ISSUE THREAD

**Issue by dmitriev02** [pepzwee/node-csgo-web-tradebot#40]
### Error Stack
I'm got error 400 when loading user inventory from SteamApis, but in site all my requests are counted, but it always load and load same inventory. When I'm in browser, all loads well.

**Comment by FreddyFish** [comment]
Please use the issue template.

**Comment by dmitriev02** [comment]
### Expected behavior
Load steam inventory with statusCode 200

### Actual behavior
Steam inventory isn't loading when trying to load them from server. Getting responseCode 400.

### Steps to reproduce the behavior

### Other
1. [Operating System]: Ubuntu 16
2. [Node.js version]: latest
3. [How did you start the script]: pm2 start app

### Error Stack
statusCode 400

**Comment by FreddyFish** [comment]
400 is bad request. Do you have Access to the API? What API are you using? And is the API you are using online?

**Comment by dmitriev02** [comment]
I'm using same url at browser and all works. But at site, it gives response 400.

**Comment by dmitriev02** [comment]
And all requests with response 400 counted at steamapis.

**Comment by pepzwee** [comment]
Send me your ``config.js`` file - hello@pepzwee.com
Remove your username and password values but keep everything else as is.

**Comment by dmitriev02** [comment]
sent

**Comment by dmitriev02** [comment]
so?

**Comment by pepzwee** [comment]
Your folder structure seems to indicate that you're not using the current original Github version. It has multiple files that aren't from this repository.

I don't provide support for modified files - and csg0.trade seems to be working fine.
