### ISSUE TITLE
What node modules do i need to install?

### ISSUE THREAD

**Issue by Kevje4** [pepzwee/node-csgo-web-tradebot#41]
Title says it all

**Comment by FreddyFish** [comment]
There is a package.json - It's not that hard.

**Comment by iDefineHD** [comment]
In node. Type 'node install' when in directory.

**Comment by FreddyFish** [comment]
No, do not listen to @iDefineHD 
To install the modules you have to use the command "npm install"

But i mean, the package.json file is there, why is this so hard for people?
You should probably not run this script, if you do not know what you are doing.

**Comment by iDefineHD** [comment]
Yeah sorry. I am dumb and it is late. Will remove past message. Do what Freddy said. Thanks for correcting.
