### ISSUE TITLE
Cannot sign in

### ISSUE THREAD

**Issue by Kevje4** [pepzwee/node-csgo-web-tradebot#43]
### Expected behavior
Website works as normal
### Actual behavior
Cannot sign in
### Steps to reproduce the behavior
I read #35 and disabled apache with "sudo service apache2 stop" and now the website wont load at all
### Other
1. [Operating System]: Ubuntu 14.04
2. [Node.js version]: Node 7.0
3. [How did you start the script]: Node index.js

### Error Stack
No errors in console

**Comment by FreddyFish** [comment]
You changed the port to 81 right?
Then go to your url/ip:81

**Comment by Kevje4** [comment]
Okay

**Comment by FreddyFish** [comment]
Yeah, and i can totally use that comment.
If you do not know how to set this up, you should not be running it.

- Dont waste your time.

**Comment by Kevje4** [comment]
I got it working it was just a misspelling in the config file
