### ISSUE TITLE
Error: Callback was already called.

### ISSUE THREAD

**Issue by MarcFryd** [pepzwee/node-csgo-web-tradebot#45]
So i was installing the script on my server and it dosen't stop to say 

1. [Operating System]:Debian 8x64
2. [Node.js version]: v6.10.3
3. [How did you start the script]: node index.js

```
Callback was already called

[!] Socket server is online.
[!] All bots online.
/var/www/html/node_modules/async/dist/async.js:903
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /var/www/html/node_modules/async/dist/async.js:903:32
    at Timeout.setTimeout (/var/www/html/lib/bots.js:70:13)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
root@locationvps:/var/www/html#


```

**Comment by FreddyFish** [comment]
Seems like there is a problem with your node modules. 
Where did you get your modules?

**Comment by MarcFryd** [comment]
With "npm install"

**Comment by FreddyFish** [comment]
Is apache installed? And why did you choose to place your files in /var/www/html/ ?

**Comment by MarcFryd** [comment]
Is apache installed?: yes
And why did you choose to place your files in /var/www/html/ ? I don't know should i place the file somewhere else

**Comment by FreddyFish** [comment]
What port are you using in your config.js? 
Apache is using port 80, so if you want to use this, delete/disable apache, or change the port in the config.js

Try to place the script somewhere else, maybe in /home/

**Comment by MarcFryd** [comment]
I'm using port 80 for the config but i stopped apache

**Comment by FreddyFish** [comment]
Weird. Are you showing me the full error?
Are you sure everything in the config is correct, including twoFactorCode, identitySecret, apikey, username, password? 

Also is the steam account you are trying this on limited?

**Comment by MarcFryd** [comment]
so i tried install all the thing with a new config.js (blank one) and it launch and it doesn't crash

**Comment by FreddyFish** [comment]
So it works now?

**Comment by MarcFryd** [comment]
so i maybe found the problem its the bot i think

**Comment by FreddyFish** [comment]
Is your bot account limited?

**Comment by MarcFryd** [comment]
I just created the account

**Comment by FreddyFish** [comment]
Did you deposit 5$/€ to the account?

**Comment by MarcFryd** [comment]
oh is this the problem ?

**Comment by FreddyFish** [comment]
Yes it is. You have to deposit 5$ to get the steamAPI key.
