### ISSUE TITLE
How do i fix signing in through steam

### ISSUE THREAD

**Issue by ToothPain** [pepzwee/node-csgo-web-tradebot#46]
1. [Operating System]: Ubuntu 16.04.2 x64
2. [Node.js version]: Latest
3. [How did you start the script]: forever start index.js

How do I fix when I click "SIGN IN THROUGH STEAM" it takes me to this page: http://imgur.com/RgAiA2d

**Comment by FreddyFish** [comment]
Delete or disable apache.

**Comment by ToothPain** [comment]
If I delete apache the site wont load.

**Comment by ToothPain** [comment]
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict m                                                                 ode

**Comment by ToothPain** [comment]
Bot (bot_1) has been logged-in.
[!] All bots online.
[!] Website server is online.
[!] Socket server is online.
(node:28469) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
fs.js:113
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^

Error: ENOENT: no such file or directory, open './polls/bot_1.json'

**Comment by iDefineHD** [comment]
Create them. Then re run the script.

**Comment by ToothPain** [comment]
I just created a polls folder and it's working now. Ty

**Comment by FreddyFish** [comment]
Another time, use the search function. This issue has been submitted so many times.
