### ISSUE TITLE
I dont have /auth/steam

### ISSUE THREAD

**Issue by kjkjkjkjkj** [pepzwee/node-csgo-web-tradebot#48]
How i can fix this?

**Comment by FreddyFish** [comment]
You are running it wrong. Dont put this is /var/www

**Comment by FreddyFish** [comment]
And uninstall Apache.

**Comment by kjkjkjkjkj** [comment]
If I unistall apache the website doesnt work.

**Comment by kjkjkjkjkj** [comment]
I fixed, now this: http://prntscr.com/fk24bu
The website dont load inventory

**Comment by FreddyFish** [comment]
The website won't work with Apache.
Uninstall or disable apache.
run your index.js file with - node index.js

Please also read the readme, for details about inventory & pricing API.
