### ISSUE TITLE
Problem with start

### ISSUE THREAD

**Issue by astroaut** [pepzwee/node-csgo-web-tradebot#49]
When i start scritp (node index.js) 
It`s crashing:
root@vps423276:/home/bot# node index.js
Bot (bot_1) has been logged-in.
[!] All bots online.
[!] Website server is online.
[!] Socket server is online.
fs.js:53
        throw backtrace;
        ^

Error: ENOENT: no such file or directory, open './polls/bot_1.json'
    at rethrow (fs.js:48:21)
    at maybeCallback (fs.js:66:42)
    at Object.fs.writeFile (fs.js:1119:18)
    at TradeOfferManager.<anonymous> (/home/bot/lib/bots.js:61:16)
    at emitOne (events.js:77:13)
    at TradeOfferManager.emit (events.js:169:7)
    at /home/bot/node_modules/steam-tradeoffer-manager/lib/polling.js:264:9
    at /home/bot/node_modules/steam-tradeoffer-manager/lib/index.js:369:4
    at /home/bot/node_modules/steam-tradeoffer-manager/lib/assets.js:163:3
    at /home/bot/node_modules/async/dist/async.js:1074:9

how to fix it?

**Comment by FreddyFish** [comment]
Check old issues.

**Comment by astroaut** [comment]
I don`t installing apache.

**Comment by astroaut** [comment]
What`s OS you can reccomend to host?

**Comment by FreddyFish** [comment]
Does not really matter, it should work on any OS. 
Read the comments on #46

**Comment by astroaut** [comment]
I need create ./polls/bot_1.json right? Whats path?

**Comment by FreddyFish** [comment]
That's the path?
You just commented it yourself.
Try it out before you comment. I'm not going to spoon feed you.

**Comment by astroaut** [comment]
I can`t find a /polls/ ...

**Comment by FreddyFish** [comment]
Then create it? 
"I need create ./polls/bot_1.json right? Whats path?" > You you said it yourself, what is the problem?

**Comment by astroaut** [comment]
What`s? I can understand, sorry. I cant search path /polls/. I need create it, but where? what`s full path

**Comment by astroaut** [comment]
Sorry, im really stupid. I fix it, thanks for help!

**Comment by astroaut** [comment]
Now inventory not uploading...

**Comment by FreddyFish** [comment]
Read the readme. 
You probably don't have access to the API.

I will give you some advice. 
Do not run this, you are not experienced enough to do so. So just walk away from this repo, it's not for you. Start out with something more simple.

**Comment by astroaut** [comment]
No why you so evil? Why you can`t be calm? I read this...

**Comment by FreddyFish** [comment]
I am calm.
I'm not evil.
I'm tired of people like you, that thinks that this is a money-machine, and will work for them within 5 minutes.

You should not run this script, because you are not experienced enough. 
Read the readme, and you will figure out whyt your inventory is not loading.

**Comment by astroaut** [comment]
idk what`s api not free
