### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by kotik1998** [pepzwee/node-csgo-web-tradebot#5]
http://prnt.sc/dynsni
(igone and look down)

**Comment by kotik1998** [comment]
![](http://image.prntscr.com/image/794338961503452cab9806a9fd8ebca5.png)

**Comment by FreddyFish** [comment]
What command are you running?
node index.js?

**Comment by kotik1998** [comment]
yes

**Comment by FreddyFish** [comment]
Did you remember install all modules?

**Comment by kotik1998** [comment]
did them all

**Comment by pepzwee** [comment]
Either you didn't install dependencies, have an old Node version or your config file is messed up.

**Comment by kotik1998** [comment]
![](http://image.prntscr.com/image/8499d247c8d243be9b8826440be383ea.png)

now i have this error

**Comment by pepzwee** [comment]
Create an empty file calles `bot_1.json` inside `polls` folder and tell me if you get any error then

**Comment by kotik1998** [comment]
Roger sir!

**Comment by kotik1998** [comment]
Error.

![](http://image.prntscr.com/image/899b23dd435446e0868c59d141f49401.png)

**Comment by pepzwee** [comment]
Add this `{}` to the `bot_1.json` file
