### ISSUE TITLE
Inventory does not load.

### ISSUE THREAD

**Issue by gold9** [pepzwee/node-csgo-web-tradebot#52]
Please wait..
![1](https://user-images.githubusercontent.com/29573710/27333125-42d5a8e0-55de-11e7-80d4-e411bdb85608.jpg)
[Operating System]: Ubuntu 14.04
[How did you start the script]: nodejs index.js

**Comment by FreddyFish** [comment]
Read the README.md

**Comment by FreddyFish** [comment]
When you figure out what the problem is.. - then good.
I will be able to fix this for you, add me on Steam. - (My website can be found on my github profile)
