### ISSUE TITLE
Trade status Could not get a price for item(s). Trade has been cancelled.

### ISSUE THREAD

**Issue by tirrom** [pepzwee/node-csgo-web-tradebot#53]
### Expected behavior
It'ss expected to steam send an trade offer

### Actual behavior
Trade status
Could not get a price for item(s). Trade has been cancelled.

### Steps to reproduce the behavior
Make an offer and TRADE

### Other
1. [Operating System]: Windows Server 2016
2. [Node.js version]: Node 6.9.5
3. [How did you start the script]: node index.js

### Error Stack
Trade status
Could not get a price for item(s). Trade has been cancelled.

**Comment by FreddyFish** [comment]
You are trying to trade items which are lower then the price set in config.js -> ignoreItemsBelow:

**Comment by tirrom** [comment]
I set ignoreItemsBelow to 0.01 now when I try to trade I'm getting this error right after "Preparing to send offer..":

Trade status
{}
