### ISSUE TITLE
How would I use a different site for the API?

### ISSUE THREAD

**Issue by FinleyCorrigan** [pepzwee/node-csgo-web-tradebot#55]
Would I just change the steam api's url to a different sites one?

**Comment by FreddyFish** [comment]
Not sure if we provide support for different API's here on this repo.
You will have to figure out yourself.

The code is open -source, it's not that hard to figure out.

**Comment by FinleyCorrigan** [comment]
Yeah thanks, I already made a little edit that changes the API. Thanks again for the help though.

**Comment by Dev-rahul** [comment]
Hey how do u change the API?
