### ISSUE TITLE
Trade status {}

### ISSUE THREAD

**Issue by tirrom** [pepzwee/node-csgo-web-tradebot#57]
### Expected behavior
Send trade offer through Steam

### Actual behavior
When I try to trade I'm getting an error right after the message "Preparing to send offer.."

### Steps to reproduce the behavior
Trade

### Other
1. [Operating System]: Windows Server 2016
2. [Node.js version]: Node 6.9.5
3. [How did you start the script]: node index.js

### Error Stack
Getting this message:
Trade status
{}

My Steamguard was enabled less than 7 days ago, could that be the reason?

**Comment by FreddyFish** [comment]
Yes, it could be the problem.

**Comment by tirrom** [comment]
At skinmine.net I'm getting the error: You must have 2FA enabled, we do not accept trades that go into Escrow but at my website all I'm getting is: {}

**Comment by FreddyFish** [comment]
Your account is not ready to trade then. Try to send a trade to someone, and see if it goes through.
