### ISSUE TITLE
I cant run it!!

### ISSUE THREAD

**Issue by kjkjkjkjkj** [pepzwee/node-csgo-web-tradebot#58]
http://prntscr.com/foh80p

Here's my problem

**Comment by iDefineHD** [comment]
You need to npm install the packages.

**Comment by kjkjkjkjkj** [comment]
How i can do this command?

**Comment by FreddyFish** [comment]
Seems like you have 0 experience with node and npm in general. You should not run this script. If you want to learn node, feel free to do so, but start with something more simple.
