### ISSUE TITLE
Trade Link Update

### ISSUE THREAD

**Issue by iDefineHD** [pepzwee/node-csgo-web-tradebot#6]
I am not sure if this is just an issue pertaining to me, but every now and again the trade link update on first arrival on the page doesn't update, therefore not allowing any trades to happen. I can only fix this by then transferring the files back over. Any suggestions?

**Comment by FreddyFish** [comment]
I'm not sure what your issue is. Can you explain a bit better?
I'm not having this issue, are you running the latest source?
Have you installled the right modules? > npm install

**Comment by iDefineHD** [comment]
yes i have used npm install to install all packages, the problem is that sometime for some reason the update tradelink just doesnt do anything, after you hit the update button. This is normally fixed with uploading the exact same files back to the server. It's a weird issue i know. i was just wondering if anyone else is experiencing and or getting the same result as me.

**Comment by pepzwee** [comment]
What browser are you using?

Uploading and replacing the files shouldn't change anything.. since the saved trade link will be placed into localstorage for that domain.

**Comment by FreddyFish** [comment]
I think i had this problem once. Did you remove the GA in index.html?
This can make the script un-useable.

**Comment by iDefineHD** [comment]
It seemed That I had when chaging files around etc. That seemed to work. Thanks guys for the help. Closed.

**Comment by FreddyFish** [comment]
You welcome! ;)
