### ISSUE TITLE
offerStatus

### ISSUE THREAD

**Issue by gold9** [pepzwee/node-csgo-web-tradebot#60]
1. [Operating System]: ubuntu 14.04
2. [Node.js version]: 
3. [How did you start the script]: nodejs index.js

How to find out whether the trade is accepted by the bot. ? Through the site

offerStatus

**Comment by FreddyFish** [comment]
What do you mean? Please explain better.

**Comment by gold9** [comment]
As on the site vystenee message like a bot will take a trade?

**Comment by FreddyFish** [comment]
I have no idea of what you are talking about.

**Comment by gold9** [comment]
How to find out confirmation of the trade and show a message?

**Comment by FreddyFish** [comment]
I'm not sure what you are talking about. But the BOT is confirming the offer in lib/bots.js at line 96.
The bot is not accepting the offer, the user is accepting the offer. The only thing the bot is doing is sending the request to the user, and confirming it using the "Mobile Authenticator"

**Comment by pepzwee** [comment]
Since the OP has not made a reply in a week I presume he got it fixed.
