### ISSUE TITLE
Help with navbar

### ISSUE THREAD

**Issue by hermanse** [pepzwee/node-csgo-web-tradebot#61]
Hi, i need help with navbar. I need move navbar to the top of the page. When i do it, site not still working. How i need change index.html to all works fine? Thanks for understanding!

**Comment by iDefineHD** [comment]
Thia is not an issue. And should not be addressed as one. It is bootstrap. So view the docs for it and change it through that, it should not take you 5 mins to do it

**Comment by hermanse** [comment]
Omg, its not boostrap. I dont want to change theme, color, or etc. Im want to move it to the top of the page. And when i change html thats not working. Yes it`s not issue, but who write this html i think know how to do it. And this work lower than 5 min.

**Comment by iDefineHD** [comment]
Yea. The frontend html is bootstrap. You can move the navbar and its contents in 2 minutes with use of the bootstrap docs ( http://getbootstrap.com/components/ )

**Comment by hermanse** [comment]
Understand me pls, when i move it, its still not working.

**Comment by iDefineHD** [comment]
If you have it as a top nav. Have you moved the subsiquent content that would populate the nav? I would nit be able to tell you without seeing your edited code anyways.

**Comment by hermanse** [comment]
try it change on your site and u see what happened

**Comment by FreddyFish** [comment]
Bro.. Listen up. If you want help, make your own changes and show us what you get. - And then we can help you. - We won't make the work for you.

**Comment by hermanse** [comment]
I'm trying to do it myself for 5 hours, and no any results. Always not working, because this im write here.

**Comment by FreddyFish** [comment]
It's pretty easy though.
Go to the bootstrap docs and you will be able to see what you should do.
It works fine here, so you are probably doing something wrong.
https://gyazo.com/dfb944eb563a4c2769385980e4f44428

**Comment by hermanse** [comment]
Huh, it's working fine without script. With script avatar not showing

**Comment by FreddyFish** [comment]
Also this is not really the place to discuss this. This is for issues with the script, not issues if the script is modified. As this is a modification to the "script" itself you will have to figure this out yourself.

**Comment by hermanse** [comment]
http://i.imgur.com/9cdp0EZ.png
This im take when move nav

**Comment by gold9** [comment]
Include in tags
<div id="app">

**Comment by hermanse** [comment]
I'll try to do it so much times... Alws still not woking, it`s possible? Xd
