### ISSUE TITLE
SSL protocol.

### ISSUE THREAD

**Issue by trylol** [pepzwee/node-csgo-web-tradebot#62]
Can you pls help me with set up ssl protocol on node? I need change index.js, right? If you have , give me example for node. On my languege no tutors to install that on node, and i dont find a good tutor on eng. Thanks for ur help and understanding <3

**Comment by iDefineHD** [comment]
This really isnt an issue and should not be posted here. Could i suggest though to google. 'Nginx reverse proxy'. Then you can use letsencrypt to ssl.

**Comment by FreddyFish** [comment]
Why would you use SSL here though?

**Comment by trylol** [comment]
There no topic with name 'help'. I have a ceritifacte from letsenycrypt, and i need set up it. I need set up ssl bcz for google site with ssl better, then without ssl. And bcz this i want to set up it. I need simple js, cuz hosting provider info dont help.

**Comment by trylol** [comment]
For ngnix server set up its easy, but i work with js so little and idk how to do it.

**Comment by FreddyFish** [comment]
Well.. SSL has nothing to do with this script.
So it should not even be posted here.
