### ISSUE TITLE
Cant save trade URL's - No install instructions

### ISSUE THREAD

**Issue by ItsCresent** [pepzwee/node-csgo-web-tradebot#63]
How are the URL's suppose to be saved when there is no DB file? Also you provide no installation instructions so had to find someone else who have a changed version of this website tell me how to install this through node.js!

**Comment by FreddyFish** [comment]
Of course there is no installation instructions. This is really, really easy to setup,  and if you have no experience with nodejs you should probably not run this. Stay away from here, and come back when you have some experience.

**Comment by pepzwee** [comment]
If you found someone else, be careful of backdoors. The lack of install instructions is intentional.
