### ISSUE TITLE
Error: ENOENT no such file or directory as /polls/bot_1.json

### ISSUE THREAD

**Issue by BlitherLlama** [pepzwee/node-csgo-web-tradebot#64]
### Expected behavior
Website starts
### Actual behavior
Website doesn't start
### Steps to reproduce the behavior
root@iskin:~# cd ../var/www/html
root@iskin:/var/www/html# nodejs index.js

### Other
1. [Operating System]: <here>
2. [Node.js version]: <here>
3. [How did you start the script]: <here>

### Error Stack
Bot (bot_1) has been logged-in.
[!] All bots online.
[!] Website server is online.
[!] Socket server is online.
fs.js:101
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^

Error: ENOENT: no such file or directory, open './polls/bot_1.json'
    at Error (native)

**Comment by iDefineHD** [comment]
Cant you look at past/closed issues? Create a polls folder. Then it will populate it.

**Comment by FinleyCorrigan** [comment]
CLOSE!
