### ISSUE TITLE
The requested URL /auth/steam was not found on this server.

### ISSUE THREAD

**Issue by BlitherLlama** [pepzwee/node-csgo-web-tradebot#65]
### Expected behavior
Steam login page appears
### Actual behavior
Error page appears
### Steps to reproduce the behavior
> http://45.63.28.67/
> sign in with steam
### Other
1. [Operating System]: <here>
2. [Node.js version]: <here>
3. [How did you start the script]: <here>

### Error Stack
Not Found

The requested URL /auth/steam was not found on this server.

Apache/2.4.7 (Ubuntu) Server at 45.63.28.67 Port 80

**Comment by iDefineHD** [comment]
This is meant to be run through node itself. Remove apache and run again.

**Comment by BlitherLlama** [comment]
What file path is it meant to be

**Comment by iDefineHD** [comment]
It isnt a path iasue. As said above uninstall apache and run it through node.

**Comment by BlitherLlama** [comment]
root@iskin:/var/www/html# node index.js
Bot (bot_1) has been logged-in.
[!] All bots online.
[!] Website server is online.
[!] Socket server is online.

The site won't let me connect however
This site can’t be reached

45.63.28.67 refused to connect.

**Comment by FinleyCorrigan** [comment]
Close the issue. I've helped him

**Comment by iDefineHD** [comment]
Pepz or he can do it.

**Comment by FinleyCorrigan** [comment]
This kids a scammer btw. http://csgosuperior.com/ . It's his site/

**Comment by FreddyFish** [comment]
What a douche.
