### ISSUE TITLE
Trade status {}

### ISSUE THREAD

**Issue by dalexhd** [pepzwee/node-csgo-web-tradebot#66]
Hi, when I try to make a trade, it shows: 
**Trade status**
1. Validating requested trade..
2. Preparing to send offer..
3. {}
How can I solve this?¿

**Comment by FreddyFish** [comment]
Your bot does not have access to trading.
Deposit 5$ to your bot account to get access.

**Comment by FinleyCorrigan** [comment]
What Freddy fish said, your bot is either trade banned/restricted, or you haven't verified your steam account. You also might not of set up your authentication properly. 

Tell us if it helped!

**Comment by FinleyCorrigan** [comment]
Can be closed.
