### ISSUE TITLE
A guy is scamming innocent people by selling your code....

### ISSUE THREAD

**Issue by FinleyCorrigan** [pepzwee/node-csgo-web-tradebot#68]
A guy added me the other day because he needed help with a steam trading site. He told me he bought the code from http://csgosuperior.com. I told him that he had been scammed, cause the code was actually free and open source (its for sale on the site for 29.99 USD). 

He then told me that he would just get a refund via paypal, and I then told him it doesn't work like that. 

I eventually found out that the guy that added me is the actual owner of the site, and he saids he has made 1000's of dollars scamming people. He has also got lots of other code for sale. 

I've told him to stop, but he is now blackmailing me,m he says he'll stop if I help him with some broken code, but if he was going to stop, then why would he need help?!

Nothing can really be done, as far as I know, but I thought I should alert people. I'll link his steam profile and github (he asked a question on here a couple of days ago).

Steam: http://steamcommunity.com/profiles/76561198126532803 (Don't click view more info on his profile, it downloads a virus).
GitHub: https://github.com/dalexhd
Site: http://csgosuperior.com/

Hopefully we can get rid of him.

**Comment by pepzwee** [comment]
> MIT License - **Permission is hereby granted**, _free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or_ **sell
copies of the Software**

Just don't help him, I doubt he has any real coding knowledge to modify the code to suit "his needs". You can go ahead and report him if he has indeed scammed you or any other people, but considering I published this under the MIT license - what he is doing is not really against the license.

**Comment by FinleyCorrigan** [comment]
Yeah I know about the license, I just wanted to alert people about him. I doubt he has coding knowledge, as everything on his site is just a copy. He hasn’t scammed me, and I hope he doesn’t scam anymore people.

**Comment by FinleyCorrigan** [comment]
He’s not including a license, and he’s also putting Copyright CSGO Superior at the bottom, and making it look like he completely designed it. 

I know he didn’t, cause he asked me to help him, and he sent me the code (I deleted some of it, but he didn’t know, that’s why he was asking questions, that’s why his bot doesn’t work).
