### ISSUE TITLE
Not login | Not steam auth files

### ISSUE THREAD

**Issue by delidolu1genc** [pepzwee/node-csgo-web-tradebot#69]
http://www.belgoturk.tk/

http://www.belgoturk.tk/auth/steam

**Comment by FreddyFish** [comment]
Disable or delete Apache.

**Comment by delidolu1genc** [comment]
And? :)

**Comment by iDefineHD** [comment]
Thats it. Disable apache/remove. Then run the node script after changing the config.

**Comment by BlitherLlama** [comment]
/auth/steam isn't a file

sudo apt-get update
sudo apt-get upgrade
sudo apt-get autoremove
sudo apt-get remove apache2

nodejs index.js

**Comment by pepzwee** [comment]
These ones drive me nuts.
