### ISSUE TITLE
Enhancement - Trade Hold.

### ISSUE THREAD

**Issue by iDefineHD** [pepzwee/node-csgo-web-tradebot#7]
If the user has a tradehold, then reject the offer for that reason, as at the minute these trade will still go through.

**Comment by pepzwee** [comment]
Whoever has the time to fix that can make a pull request and I will merge it.

**Comment by fortza** [comment]
res.json({
						success: true,
						code: code,
						amount: checksum,
						tid: r.tradeofferid,
						items: names
					});
				}
			});
		}
	});
	  } else {
     logger.error('Error sending trade offer');
     logger.debug(err);
     res.json({
      success: false,
      error: "You need to activate Steam Mobile Authentificator."
     });
    }
   }
  });
});

this help ?

**Comment by pepzwee** [comment]
https://github.com/pepzwee/node-csgo-web-tradebot/commit/7abdaa201060e1e075d4f60b0265fa8a53e5dfbf

**Comment by epdev** [comment]
> Steam uses the larger value between you and the other user

@pepzwee It should work well. Have you checked that it gets only the bot escrow data?
