### ISSUE TITLE
How to install node csgo web tradebot ?

### ISSUE THREAD

**Issue by delidolu1genc** [pepzwee/node-csgo-web-tradebot#71]
I set up this script as follows. But I can not login in the website.

1. Installed DigitalOcean.com 64Bit Ubuntu
2. sudo apt-get update
3. sudo apt-get install nginx
4. sudo apt-get install mysql-server
5. sudo mysql_install_db
6. sudo mysql_secure_installation
7. sudo apt-get install php5-fpm php5-mysql php5-mcrypt 
8. sudo apt-get install curl libcurl3 libcurl3-dev php5-curl
9. sudo php5enmod curl
10. curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
11. sudo apt-get install -y nodejs
12. mkdir -p /home/www/html
13. Uploaded web files
14. and no login to websites.

NOTE: The work you do is really worth a job. But I really ask you to share some explanations for those who want to do this job. At least I think it should be an installation instruction.

Thank you.

**Comment by iDefineHD** [comment]
you should only set up nginx as a reverse proxy, you simply run the script with node index.js. After changing the details in the config file.

**Comment by FreddyFish** [comment]
If you have 0 experience you should not run this.

**Comment by delidolu1genc** [comment]
Thank you IDefineHD.

**Comment by iDefineHD** [comment]
Np. Close the issue please.
