### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by delidolu1genc** [pepzwee/node-csgo-web-tradebot#72]
--Removed due to invalid install instructions, possible backdoor method--

**Comment by pepzwee** [comment]
Cute, but no go. Never install node modules like that, probably added a backdoor to a module.

**Comment by delidolu1genc** [comment]
Are not you the developer of this software? If there is a possibility, why do not you prevent it. What kind of clearness was there in the setup instructions, would you disclose it to me? I am not a scammer or a malicious person. CS: GO I buy and sell the keys and I want to do this with this script.

**Comment by iDefineHD** [comment]
Yes. He is. Although. The guide you created is bad on several levels. I will clear up what needs to be changed later for you.

**Comment by FreddyFish** [comment]
Why in the world would you download modulets from a untrusted source, when it can be done from the npm install command?

**Comment by delidolu1genc** [comment]
@FreddyFish You can change this. For this you did not need to be a tutorial. I am not experienced in this matter, I do not know more commans.

If I were such an experienced person, I would have developed and used my own software. Thank you for your answers, I hope you can create a narration and help people.

See you

**Comment by delidolu1genc** [comment]
@iDefineHD 

16 hours has still not loaded inventory. Do you know anything about this? Thank you
 for help.

http://146.185.182.128/

**Comment by pepzwee** [comment]
I'm going to take a wild guess and say that you didn't get a SteamApis.com key that has the necessary endpoints enabled.

Endpoints
- Steam Inventory
- Market Items

**Comment by delidolu1genc** [comment]
I have received a Steamapis.com key, but do I need to take it for a fee?

**Comment by pepzwee** [comment]
SteamApis.com is a paid service.

**Comment by delidolu1genc** [comment]
I understand.

Can I get another service? for example; csgofast.com API or other. Which file I need to edit

**Comment by FreddyFish** [comment]
As i told you last time.
If you have zero experience with node and javascript in general you should probably not run this at all. 
It's open source, go look in the code yourself? There is not a lot of files in the repo, so it can not take more then a few minutes to figure it out.

No one here is going to spoon feed you.
