### ISSUE TITLE
Errors Related to Ports When Running Script

### ISSUE THREAD

**Issue by FinleyCorrigan** [pepzwee/node-csgo-web-tradebot#73]
Hi,

I've been trying to run the script, but keep getting errors relating to ports. I don't have Nginx installed or anything, but used too. Someone please help me.

### Other
1. [Operating System]: Ubuntu 16.04
2. Node.js Version: 6.11.1
3. [How did you start the script]: node index.js OR pm2 restart

### Error Stack

root@csgotradingco:/var/www/html# node index.js
Bot (bot_1) has been logged-in.
[!] All bots online.
[!] Website server is online.
[!] Socket server is online.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::80
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at Object.<anonymous> (/var/www/html/index.js:20:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

**Comment by FreddyFish** [comment]
Port 80 is in use. 
Figure out whats running in port 80.

Or change the port in the config.

**Comment by FinleyCorrigan** [comment]
I figured that, and I have tried to see if anything is using Port 80. I have UFW enabled, so only Port 80 is open. Should I open Port 81 and change it in config? Is that all I need to do to change the Port?

**Comment by FreddyFish** [comment]
Well if you want to run the script on port 81 yes. 
What is your website URL?

**Comment by pepzwee** [comment]
``sudo lsof -i :80`` should tell you what process/PID is using the port.
