### ISSUE TITLE
CSGOFast API 502 Bad Gateway

### ISSUE THREAD

**Issue by Glavatar** [pepzwee/node-csgo-web-tradebot#75]
https://api.csgofast.com/price/all - Is now returning 502 Bad Gateway, don't know if it's getting fixed soon or not. It is causing website to set prices to all items to $NaN because it is constantly trying to fetch prices from csgofast. Any other reliable API for high prices ?

**Comment by pepzwee** [comment]
Removed CSGOFast as a pricing source https://github.com/pepzwee/node-csgo-web-tradebot/commit/2f8836749f3a10aa756c19bac22f743f0c324cc8

SteamApis provides high tier items.
