### ISSUE TITLE
Trade status not displaying a error

### ISSUE THREAD

**Issue by IMaFED** [pepzwee/node-csgo-web-tradebot#76]
First of i want to say, I do have money on my steamapi and the bot is not on any kind of tradehold.
And i know there's a issue about this before but its closed and market invalid. (So i hope it's ok that i make a new one)

Sometimes when I press "Trade" it works and sometimes i get the "Trade status {}".
My first guess was that it was the steam api that was overused so i changed it to one i only use with the bot. Still happens.
It usually works if i restart the app. So my next guess was that the server load was to high, but it never comes close to even 5% cpu and ram is like 60%.

I do run it as a pm2, but that should not make any difference right?

The index.html sais
`<strong v-else>{{ offerStatus.error }} </strong>`
So i guess there's supposed to be a error message where the "{}" is?

Where do i begin to get the error message to display correctly?

Thanks in advance!

**Comment by pepzwee** [comment]
Please provide me your trade URL here: hello@pepzwee.com

**Comment by IMaFED** [comment]
Sent you the trade url.

**Comment by IMaFED** [comment]
@pepzwee 
It displays an error message new, (And i only gotten it 1 time where before i would have gotten it like 10+) did you change something with the steamapis? Or is this just a lucky coincidence?

**Comment by pepzwee** [comment]
No changes were made. Most likely Steam being wonky at that time is what caused your empty errors.
