### ISSUE TITLE
Calling an asynchronous function without callback is deprecated

### ISSUE THREAD

**Issue by Glavatar** [pepzwee/node-csgo-web-tradebot#77]
I've managed to setup everything, and its working flawless but once started testing, when the website sends the offer it constantly shows this error. Is it something I should be worried about ?

![01bwz3ryqtqfwuummrhhiw](https://user-images.githubusercontent.com/26853038/29037692-fa8cf146-7ba4-11e7-9ebc-df01ec921fb0.png)

**Comment by FreddyFish** [comment]
No. Just ignore it.
