### ISSUE TITLE
Issue loading scripts

### ISSUE THREAD

**Issue by sockamrt1** [pepzwee/node-csgo-web-tradebot#79]
### Expected behavior

Inventories load, steam auth works, and item values are found.

### Actual behavior

Inventories are not loading, steam auth returns 404, and item values are not found.

### Steps to reproduce the behavior

I changed by websitePort to 81 to solve [this error](https://github.com/pepzwee/node-csgo-web-tradebot/issues/73), I have purchased my SteamApi.com key, my bot account has $5 deposited, apache is not installed and [as you can see](http://prntscr.com/g7h9e8) there are no errors in the terminal.

### Other
1. Operating System: Linux (Ubuntu 14)
2. Node.js version: v8.3.0
3. How did you start the script: node index.js

### Error Stack

[Loads of errors.](https://prnt.sc/g7h8ln) I can see that it's trying to find it through my domain I'm just not sure why or where it's doing that.

**Comment by FreddyFish** [comment]
Do you access the website with domain:81?

**Comment by sockamrt1** [comment]
No I just visit domain.com

**Comment by FreddyFish** [comment]
Well there you have it. Thats the problem. If you arr running with port 81 you should visit - domain.com:81. If port 80 domain.com is fine

Sounds like some kinda web service is using port 80 if you can access your website like that.

**Comment by FreddyFish** [comment]
What is your URL/domain?

**Comment by sockamrt1** [comment]
icyskins.com

Adding the ports doesn't appear to work. Could this be a DNS issue?

**Comment by FreddyFish** [comment]
You have a web server running on port 80.  You have run the script using node index.js then go to icyskins.com:81 and see if it works.

But i will advice you to shut down the web server you are running, and just use port 80 instead.

**Comment by pepzwee** [comment]
Any web server should be turned off - unless you know how to add a reverse proxy for this script.
That includes but is not limited to: 

- Apache
- Nginx

**Comment by pepzwee** [comment]
I also suggest changing your credentials once you've fixed the web server issue.

- Reset SteamApis.com key
- Reset Steam API key
- Change bot account password and/or reset 2FA
