### ISSUE TITLE
How to configure Steam auth?

### ISSUE THREAD

**Issue by epdev** [pepzwee/node-csgo-web-tradebot#8]
There is no "/auth/steam" folder. How should I set it up?

**Comment by pepzwee** [comment]
There's no `auth/steam` folder because it shouldn't exist. It's a route that is handled by express.

**Comment by FreddyFish** [comment]
Exactly. Set it up in the config.js

**Comment by Dakshster** [comment]
How do I find the TwoFactor Code tho? I've the Identity and Shared Secret.

**Comment by FreddyFish** [comment]
What do you mean by that @Dakshster ?

**Comment by pepzwee** [comment]
@Dakshster shared secret is same as two factor code

**Comment by Dakshster** [comment]
Ohh Okay, Thanks 👍
