### ISSUE TITLE
When i try to start index with this command nodejs index it gives me fallowing error:

### ISSUE THREAD

**Issue by tuz1k** [pepzwee/node-csgo-web-tradebot#81]
I installed all the modules and  inserted my info into config file however I'm getting this error when i try to start index.js: 
root@ubuntu-512mb-lon1-01:/home/trade# nodejs index
Bot (bot_1) has been logged-in.
[!] All bots online.
[!] Website server is online.
[!] Socket server is online.
fs.js:101
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^

Error: ENOENT: no such file or directory, open './polls/bot_1.json'
    at Error (native)
and also there is no such a file as "polls" and if i start the index with pm2 it doesn't show inventory of the bot and users inventory

**Comment by iDefineHD** [comment]
Please read past issues. Create the polls file and also change the config file with the correct information.

**Comment by FreddyFish** [comment]
For polls issue, look at @iDefineHD's comment.
For not loading inventory, read the readme.
https://github.com/pepzwee/node-csgo-web-tradebot/blob/master/README.md

**Comment by tuz1k** [comment]
thanks fixed

**Comment by FinleyCorrigan** [comment]
CAN BE CLOSED @pepzwee
