### ISSUE TITLE
I bought steamapi and payed 7.5 euros and enabled those end points however when i press trade i get this error.

### ISSUE THREAD

**Issue by tuz1k** [pepzwee/node-csgo-web-tradebot#82]
Trade status
Could not get a price for item(s). Trade has been cancelled.

**Comment by grossix** [comment]
I would advice people to not help this guy out, he is selling this script for profit on his site.
Check it out before he deletes it to cover up.

http://tuz1k.com

**Comment by FinleyCorrigan** [comment]
We need more info.
