### ISSUE TITLE
How to add bonus system?

### ISSUE THREAD

**Issue by FinleyCorrigan** [pepzwee/node-csgo-web-tradebot#83]
Hey,

I was wondering how you could add a bonus system? Like +2% if the person puts the site name in their steam name.

Hope someone can help!

**Comment by FreddyFish** [comment]
What do you mean?
You create it of course

**Comment by FinleyCorrigan** [comment]
@FreddyFish I mean does anyone know of any code that could help me do so, or tutorial?

**Comment by FreddyFish** [comment]
There is no such thing. You have to create it yourself.
