### ISSUE TITLE
/auth/steam Not Found

### ISSUE THREAD

**Issue by tuz1k** [pepzwee/node-csgo-web-tradebot#84]
### Other
1. [Operating System]: Ubuntu 140.04
2. [Node.js version]:  1.0
3. [How did you start the script]: nodejs index

after i launch everything it gives me this 
root@TradeItems:/home/trade# nodejs index
Bot (bot_1) has been logged-in.
[!] Website server is online.
[!] Socket server is online.
[!] Prices are updated.
Steam Guard App Code: [FloatChecker:Progress] Starting to acquire floats for bot "bot_1". This can take a while if you have a lot of items.
[FloatChecker:Progress] Done floats for bot "bot_1".
[!] All bots online.

BUT then i still can't sign in since it says not found why ?

**Comment by FreddyFish** [comment]
Add me on steam and i will help you.
/Id/freddyervild

**Comment by pepzwee** [comment]
Disable apache or nginx.

**Comment by leosjoberg** [comment]
I'm having the same issue, any solutions?

**Comment by pepzwee** [comment]
Disable apache or nginx.

**Comment by Gooket** [comment]
One more question.
After authorization, an error occurs

> Cannot GET //auth/steam/return

If you delete one extra /, then the authorization is successful, could you tell me how to fix this bug?
