### ISSUE TITLE
Something went wrong.. please try again! (401)

### ISSUE THREAD

**Issue by tuz1k** [pepzwee/node-csgo-web-tradebot#87]
I did everything and i payed for steamapi but it still doesn't load bots and users inventory  it says Something went wrong.. please try again! (401) and i started the index.js with pm2 and even bot is online

**Comment by pepzwee** [comment]
``401`` either means that you haven't activated the right API endpoints on SteamApis.com or the key is wrong.

**Comment by tuz1k** [comment]
No my steamapi is correct would you like to text me on steam my name is tuz1k i'm in your friend list

**Comment by pepzwee** [comment]
I'm pretty sure it's not correct.
https://steamapis.com/projects - did you enable access to those endpoints in the panel?

**Comment by tuz1k** [comment]
yes i did http://i.imgur.com/aihg8Um.png

**Comment by tuz1k** [comment]
http://i.imgur.com/WOCxn1T.png and my api does work since i can see everything in my inventory

**Comment by pepzwee** [comment]
Well if you can see everything in your inventory you should not be seeing the ``401`` error?

**Comment by tuz1k** [comment]
nvm i made a error in script sorry

**Comment by tuz1k** [comment]
text me i have offer for you id/tuz1k/
