### ISSUE TITLE
Need help with installation

### ISSUE THREAD

**Issue by F4ri0us** [pepzwee/node-csgo-web-tradebot#88]
Hello,

I have just discovered your script (by the way, thank you very much for the work), I have two questions to ask you:

1 / This is a script that works only with Node.js, is that right? Does the script need a database to work?

2 / To install the script, send all the source files to our server and modify the file config.js? Does it have other files to modify?

thank you very much

**Comment by iDefineHD** [comment]
Yes,  and no it doesnt need a database. You can modify any file how you would like. But yws the config is what you will need for it to work.

**Comment by F4ri0us** [comment]
Hello iDefineHd,

Thank you,
2 / To install the script, send all the source files to our server and modify the file config.js? Does it have other files to modify?

**Comment by iDefineHD** [comment]
No problem. I also answered that above.

**Comment by FreddyFish** [comment]
Thats correct.
And once done, start with "node index.js"

**Comment by F4ri0us** [comment]
Thanks a lot for your answers

What price to customize the basic design?
What are your tips for getting started with this site style quickly?

**Comment by iDefineHD** [comment]
You should be able to do it yourself. But add me if you want help. http://steamcommunity.com/id/iDefineHD/

Site style? Css?

**Comment by F4ri0us** [comment]
Yes, Change the colors and maybe the structure

**Comment by F4ri0us** [comment]
Hello,

In the config.js file, I need to fill in identitySecret, do I find this information or on Steam?

Thank you

**Comment by pepzwee** [comment]
Use this to get your identity and shared secret values: https://github.com/Jessecar96/SteamDesktopAuthenticator

> Go to the folder maFiles you should see some (depending on how many acounts are running on sda) .maFile files. They are all named like <steamid64>.maFile find the one you need and open it in your text editor. Just look through the file until you find shared_secret and identity_secret.
- https://dev.doctormckay.com/topic/1000-shared-secret-and-identity-secret/

**Comment by F4ri0us** [comment]
I just configure the program and when I look at the .maFile file that the program generated, I have a large amount of encrypted code I guess. How to recover identitysecret in?

**Comment by pepzwee** [comment]
You have to remove encryption under "Setup Encryption", otherwise the file will be encrypted.
https://media.pepzwee.com/1e3154c.png

**Comment by F4ri0us** [comment]
Perfect, I recover the data.
Thank you very much @pepzwee.

Do you advise me to use Steam Desktop Authenticator for bots? Is this really reliable?

**Comment by pepzwee** [comment]
I don't use Steam Desktop Authenticator for my bots, because they are bots and I've already written scripts for them to handle trading and everything I'll need.

I use it on my main and alt accounts that I do manual trading with since it's rather easy to use and I don't have to find my phone every time I need to accept something. It's reliable and safe to use as far as I know.

**Comment by F4ri0us** [comment]
Ok, the bot is automatic for exchanges on your script. I do not need to generate a token on each exchange ?!

**Comment by pepzwee** [comment]
The bot does everything automatically. I do suggest you to familiarize with the code before you use it in production though.

**Comment by F4ri0us** [comment]
Yes, I started looking at the code. I just installed the files on my server but my host is in maintenance.

**Comment by pepzwee** [comment]
Also.. this script will not run with Apache or Nginx unless you know how to setup reverse proxies.

**Comment by F4ri0us** [comment]
I apache on the server. What would it be like configuration?

**Comment by pepzwee** [comment]
I don't know what configuration Apache would need. Keep in mind your host would also have to be able to run Node scripts.

**Comment by F4ri0us** [comment]
My hosting is able to run Node.js but it works with Apache. Do you advise me which hosting service to run the script? There is an HTML file so we must apache or another distribution.

**Comment by pepzwee** [comment]
You don't need Apache nor Nginx. Serving HTML files is done within the script you don't need to worry about that.

**Comment by F4ri0us** [comment]
Agree and you advise me which host to run your script?

**Comment by pepzwee** [comment]
Any host that is able to run Node.js scripts will do.

**Comment by F4ri0us** [comment]
Yes but the problem is that apache is already installed and we can not delete it. You can not advise me a host?

**Comment by pepzwee** [comment]
I mainly use these services and their VPS/Dedicated servers
DigitalOcean, Vultr, OVH

**Comment by F4ri0us** [comment]
I have already used OVH. The problem is that I do not know how to configure a Linux distribution, I use the Plesk panel. to help me. If apache is enabled, must Nginx be enabled for your script to work?

**Comment by pepzwee** [comment]
No, the easiest option is to have both disabled. If you can't have them disabled you need to setup a reverse proxy.

**Comment by F4ri0us** [comment]
Precisely, Nginx integrates a Reverse Proxy Server through Plesk.
