### ISSUE TITLE
need help with WebSockets error

### ISSUE THREAD

**Issue by vladbuich** [pepzwee/node-csgo-web-tradebot#89]
everything worked good, before i added a SSL certificate to server. And now there is an issue with websockets: [Error] WebSocket connection to 'wss://../socket.io/?EIO=3&transport=websocket&sid=CX5GYgJ61Qc78kinAAAT' failed: Unexpected response code: 400

when making trades due to this error #tradeoffer modal does not appear, but in console log i can see a message with the new trade
Does anybody know any solutions?

**Comment by pepzwee** [comment]
How did you add that SSL certificate?

**Comment by vladbuich** [comment]
To be honest I don't know exactly. It was added throw the server provaider. By the way the server running on nginx (port 80 & 443) listening port 8080, where I run node js project

**Comment by pepzwee** [comment]
So in the script config file it's listening on port ``8080`` and nginx is acting as a reverse proxy? You need to add some specific nginx rules to work with socket.io if that's the case.

**Comment by pepzwee** [comment]
This is how csg0.trade server block looks like
https://gist.github.com/pepzwee/2e1f4e0f7f9ec29c7dfca8fabd48dfa5

**Comment by vladbuich** [comment]
Thank you for your last response I'll try it a bit later

**Comment by vladbuich** [comment]
thank you, it solved the error. but the window #tradeoffer still doesn't appear when i push trade button. it just reloads a page, however i can see a trade offer in steam account. do you know why does it reload page?

**Comment by pepzwee** [comment]
Do you see any errors in the dev tools console when you press the trade button. (Not talking about node console but web console)

**Comment by vladbuich** [comment]
no, it doesn't show any errors. i can't understand why it's reloading after this code in app.js
`$('#tradeoffer').modal('show');
                        socket.emit('get offer', {
                            user: this.userInventorySelected,
                            bot: this.botInventorySelected,
                            bot_id: this.selectedBot,
                            steamID64: this.user.id,
                            tradelink: localStorage[this.user.id]
                        });`
and if i go though debugger in chrome the trade offer window appears for a second and page reloads

**Comment by vladbuich** [comment]
got the error: WebSocket is already in CLOSING or CLOSED state.

**Comment by vladbuich** [comment]
restarted the app and again no errors just page reloading
