### ISSUE TITLE
TrashPrice in validateOffer

### ISSUE THREAD

**Issue by epdev** [pepzwee/node-csgo-web-tradebot#9]
It seems to me that the "trash price" was not included in validateOffer.

**Comment by fortza** [comment]
any fix for this ?

**Comment by fortza** [comment]
epdev how can i add trash price in validateOffer

**Comment by fortza** [comment]
**replace with this** 

Trade.prototype.getPrice = function(name, rateType, itemType) {
     if (this.prices[name] < 1)
	 {return -1;}
	 else
    {return this.prices[name] * config.rates[rateType][itemType.name] || 0;}
}

**replace with this** 

if(obj.user.length) {
        self.getInventory(obj.steamID64, '730', '2', (err, data) => {
            if( ! err) {
                let userInventory = data;
                for(let i in userInventory) {
                    let item = userInventory[i];
					 let flag = self.getPrice(item.data.market_hash_name, 'user', item.item_type);
                    if(obj.user.indexOf(item.assetid) !== -1 && flag!=-1) {
                        userCount = userCount + 1;
                        userValue += self.getPrice(item.data.market_hash_name, 'user', item.item_type);
                    }
                }

 **ALL THIS REPLACE IN /lib/index.js**

**Comment by xChr11s** [comment]
Did you test it ?

**Comment by fortza** [comment]
yes

**Comment by fortza** [comment]
http://prntscr.com/ej1wod
