### ISSUE TITLE
I can not install the script

### ISSUE THREAD

**Issue by F4ri0us** [pepzwee/node-csgo-web-tradebot#90]
Hello,

I have a VPS but I can not install the script. 
I used a VPS with Plesk. So I'll reinstall my VPS with a Debian 9 distribution this afternoon.
1 / I install Debian 9 on my VPS.
2 / I install Node.js.

Are there other things to install?

I thank you in advance

**Comment by FreddyFish** [comment]
No. Edit your config file, and start it with node index.js

**Comment by F4ri0us** [comment]
I do not know the command lines to run the file index.js with node ...

**Comment by F4ri0us** [comment]
The site is displayed correctly but you must run index.js with node. I am blocked. I connect SSH to my VPS to run the command node index.js but it does not find the file because I must not be in the correct directory. What is the command to search the directory with an Ubuntu distribution?

**Comment by pepzwee** [comment]
`npm install` will install the modules

**Comment by F4ri0us** [comment]
@pepzwee, Node JS and Express are already installed

root@vpsxxxxx:~# npm install nodejs
npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

+ nodejs@0.0.0
added 1 package in 1.357s
root@vpsxxxxx:~# npm install express
npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

+ express@4.15.4
updated 1 package in 1.218s
root@vpsxxxxx:~# node -v
v8.4.0

**Comment by pepzwee** [comment]
Unless you placed the script files in the ``/root`` directory you've incorrectly installed express. Go to the folder where the script files are located at and run ``npm install`` which will install all modules automatically.

**Comment by F4ri0us** [comment]
root@xxxxxxx:~# cd /var/www/vhosts/xxxxxxxxxxx/httpdocs
root@xxxxxxxxx:/var/www/vhosts/xxxxxxxxx/httpdocs# npm install
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

I'm sorry, I'm starting on Linux and I'm trying to understand the commands ...

**Comment by pepzwee** [comment]
You need to install ``git`` to your machine.

```
sudo apt-get update
sudo apt-get install git-core
```

**Comment by F4ri0us** [comment]
@pepzwee THANK YOU VERY MUCH.
I was able to run the node index.js command and it works fine.

Bot (bot_1) has been logged-in.
[!] Website server is online.
[!] Socket server is online.
Steam Guard App Code: [FloatChecker:Error] Could not get inventory for "bot_1", can't set floats.
[!] All bots online.

So here I can close my SSH console and the bot will stay connected? If I add bots, I need to restart index.js?

**Comment by pepzwee** [comment]
If you close your SSH console the script will exit and not work. To have it run 24/7 you have to install an additional module.

`npm i -g pm2`

Then to start your script

`pm2 start index.js -n "Tradescript"`

Then to restart your script

`pm2 restart 0`

Then to stop your script

`pm2 stop 0`

After that you can start it again with

`pm2 start 0`

If you add bots you need to restart.

**Comment by F4ri0us** [comment]
Thank you very much for all your explanations. I just installed the add-on module and it works. It's not easy when you start ... Thank you very much for your patience.

**Comment by F4ri0us** [comment]
Sorry @pepzwee, I forgot to ask you a question:
Setting npm install, does this install Node JS? Or should it be installed?

**Comment by FreddyFish** [comment]
What version of node.js are you running on your VPS?
