### ISSUE TITLE
Getting Steam login emails

### ISSUE THREAD

**Issue by Wh0egs** [pepzwee/node-csgo-web-tradebot#91]
Im getting this Email since installing the  script:

Hello xxxxxxx
--
Here is the code you need to change your Steam login credentials

 is that normal or is it just a coincidence?

**Comment by iDefineHD** [comment]
No this is not normal, but the script in no way asks or changes anything on steam. All it does is log in and create offers.

**Comment by pepzwee** [comment]
You have Steam Guard enabled without two-factor authentication. You can't use this script while two-factor authentication is not enabled. (Well you can but you're going to have to check your email every time the script restarts)

**Comment by DakshMiglani** [comment]
I think @pepzwee should close this issue as the creator hasn't been responding and the error is not because of this library.
