### ISSUE TITLE
<Title> tag can not be modified

### ISSUE THREAD

**Issue by F4ri0us** [pepzwee/node-csgo-web-tradebot#92]
Hello,

I encountered a problem with the <title> tag on the index.html page. I modified the beginning of this tag in the config.js file and changed the rest of the tag in the index.html file.

The change to the config.js file appears correctly but can not change the tag in the index.html file. If I delete the content of this tag and display the html content of my page, my <title> tag is empty but it still shows me on my Internet window Web-based websitename.

Is there another file to edit?

thank you very much

**Comment by FreddyFish** [comment]
What do you mean? Of course its empty if you delete the <title> tags in index.html, the one in config.js is loaded after the <title> one.
