### ISSUE TITLE
Error 400 - can't load bot's inventory

### ISSUE THREAD

**Issue by rafaelguedes** [pepzwee/node-csgo-web-tradebot#93]
### Expected behavior
Loading bot's inventory

### Actual behavior
Bot's inventory doesn't load  

### Steps to reproduce the behavior

Bot (bot_1) has been logged-in.
[!] Website server is online.
[!] Socket server is online.
[FloatChecker:Error] Could not get inventory for "bot_1", can't set floats.
[!] All bots online.

I've bought the correct endpoints with steamapis.com.
The api keys are correctly placed in config.js (I guess).
I'm running this locally.

### Other
1. Operating System: macOS
2. Node.js version: v6.11.2
3. How did you start the script: node index.js

### Error Stack
Error 400 ('Something went wrong...please try again')

Browser console:
https://gyazo.com/71b8c919486890f03b8a3f0999356ecb

**Comment by FreddyFish** [comment]
Add me on steam and i will try to help you out.

**Comment by rafaelguedes** [comment]
Thanks @FreddyFish. 
My inventory was set for friends.
Now it's loading the inventory.
Thanks a lot.
