### ISSUE TITLE
floats and stickers for user

### ISSUE THREAD

**Issue by vladbuich** [pepzwee/node-csgo-web-tradebot#95]
Could you guys give an advice how to make function of getting floats for user's inventory? I couldn't do it myself. And is it possible to define stickers img by stickers id, which i can get through csgo-float lib
Thank you in advance

**Comment by DakshMiglani** [comment]
@vladbuich Chek https://github.com/pepzwee/node-csgo-web-tradebot/blob/master/lib/bots.js there's a float checker in there.

**Comment by vladbuich** [comment]
@DakshMiglani yes, i know, but it's another way to get float of user's inventory
