### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by mattmad16** [pepzwee/node-csgo-web-tradebot#96]
First time i try to configurate a website 
http://138.197.190.30
If i press into "Sign in through steam" it gives me error (you can try it for yourself)
Steam api is okay 
Steam apis i'm not sure (i did not pay anything, just used the api found into the apis site) 
Sorry for my really bad english

**Comment by FreddyFish** [comment]
Disable apache.

**Comment by mattmad16** [comment]
Hi Freddy, how?

**Comment by FreddyFish** [comment]
sudo apt-get remove apache2

**Comment by mattmad16** [comment]
Nope...
ERR_CONNECTION_REFUSED
Now i cannot connect to the pace :(

**Comment by mattmad16** [comment]
Now i did apt-get install apache2 again, it works but i still cannot sign in into steam

**Comment by FreddyFish** [comment]
You do not want to have apache installed. Delete or disable it. 

After run the inde.js file with node index.js

**Comment by mattmad16** [comment]
still doesn't work

**Comment by FreddyFish** [comment]
Do you have node installed?

**Comment by mattmad16** [comment]
apt-get install node, right?

**Comment by FreddyFish** [comment]
No, install it using NVM to get the latest version.

**Comment by mattmad16** [comment]
btw file are placed into var->www, is that right? where do i have to place them?

**Comment by mattmad16** [comment]
ok, doing it now, i'm following this guide https://github.com/creationix/nvm

**Comment by FreddyFish** [comment]
Does not matter where you place them.
Install latest version of node using NVM, go to project folder and run npm install and node index.js

**Comment by mattmad16** [comment]
project folder? how can i move there?

**Comment by FreddyFish** [comment]
Project fooder = dir of script (node-csgo-web-tradebot)

**Comment by mattmad16** [comment]
how can i move into that dir?

**Comment by FreddyFish** [comment]
How would i know where you placed it? :D Im guessing you placed it in var/www?

**Comment by FreddyFish** [comment]
Add me on steam and i can help you. Found on my github profile.

**Comment by DakshMiglani** [comment]
@mattmad16 Here's a guide for installing node with nvm:
https://www.digitalocean.com/community/tutorials/how-to-install-node-js-with-nvm-node-version-manager-on-a-vps

**Comment by pepzwee** [comment]
Tutorial: https://steamapis.com/projects/node-csgo-web-tradebot
