### ISSUE TITLE
Trade status {}

### ISSUE THREAD

**Issue by F4ri0us** [pepzwee/node-csgo-web-tradebot#99]
Hello,

When I validate a trade with the bot, I have the following status: {}

I want to point out that my bot has dual authentication system enabled on Steam for over 15 days and I have been able to accept trades manually with my other accounts. By cons, I could bought in the market Steam end of the month.

The problem comes from or?

I would also like to bring up on the inventories the float of the arms and the stickers. How should I do it ?

Thank you very much

**Comment by FreddyFish** [comment]
Do you use the steamAPI key from your bot account? If not, try it out.
Did you remember to deposit 5 EUR/USD to the account?

**Comment by DakshMiglani** [comment]
can you show us your config file or check if you added the api key correctly or not.

**Comment by F4ri0us** [comment]
Hello,

@FreddyFish, I pay a license every month at SteamApis and this one is up to date and works well. I already credited my bot Steam of 5 €, more than 20 days ago. The only restriction I have on Steam is buying and selling items on the Steam market. This option will be unlocked at the end of the month.  I've made over 100 trades from a Steam account to my bot and its works fine. On the other hand, I never tried to trade my bot to another Steam account.

@DakshMiglani, The API keys have been added to the config.js file. Steam authentication works very well and SteamApis too.

Best regards

**Comment by F4ri0us** [comment]
I have a level up of my Bot Steam up to level 28 but I still have the same problem.

**Comment by pepzwee** [comment]
Email me your ``config.js`` file contents where the bot username and password is removed but keep everything else as it is.

hello@pepzwee.com

**Comment by F4ri0us** [comment]
Hello @pepzwee,

The file has been sent to your address hello@pepzwee.com.

Thank you

**Comment by pepzwee** [comment]
Hmm, nothing seems to be wrong with your config. I presume you have the correct secret codes as well.
Is the script up-to-date?

**Comment by F4ri0us** [comment]
@pepzwee ,
I was wrong on twoFactorCode, I just changed the value and I typed the command mp2 restart 0 but I still encounter the same problem on the trades. I checked all the bot values.

I downloaded the script 3 weeks ago so should be the latest version?

The problem can not come from Cloudflare and the SSL connection?

**Comment by pepzwee** [comment]
It's ``pm2 restart 0`` not ``mp2``. If you downloaded it 3 weeks ago then you're not on the latest version, there's been a few new commits https://github.com/pepzwee/node-csgo-web-tradebot/commits/master

**Comment by F4ri0us** [comment]
@pepzwee , sorry I type the command PM2 and not MP2.
I have done a lot of modification on index.html and css files. If I install the new files in the script, can I keep index.html and the CSS files or are there also changes to those files?

**Comment by pepzwee** [comment]
I'm not sure, check the commits and see if they have updated those files.

**Comment by F4ri0us** [comment]
I only modified the file prices.js, only change to make. Still not working. The problem can not come from CloudFlare?

**Comment by pepzwee** [comment]
Do ``pm2 logs 0`` and see if you have any errors. CloudFlare should not be an issue, are you running your site through nginx?

**Comment by F4ri0us** [comment]
Apache and Nginx are disabled on my server.

![services](https://user-images.githubusercontent.com/31404909/30541025-d7792134-9c79-11e7-87e9-8c509786ec60.png)

pm2 logs 0 : 

`
[TAILING] Tailing last 15 lines for [0] process (change the value with --lines o                                                                                                                                                             ption)
/root/.pm2/logs/CSGOTrading-error-0.log last 15 lines:
0|CSGOTrad | Error: ENOENT: no such file or directory, open './polls/bot_1.json'
0|CSGOTrad | (node:29276) [DEP0013] DeprecationWarning: Calling an asynchronous                                                                                                                                                              function without callback is deprecated.
0|CSGOTrad | Error: ENOENT: no such file or directory, open './polls/bot_1.json'
0|CSGOTrad | (node:29305) [DEP0013] DeprecationWarning: Calling an asynchronous                                                                                                                                                              function without callback is deprecated.
0|CSGOTrad | Error: ENOENT: no such file or directory, open './polls/bot_1.json'
0|CSGOTrad | (node:29349) [DEP0013] DeprecationWarning: Calling an asynchronous                                                                                                                                                              function without callback is deprecated.
0|CSGOTrad | Error: ENOENT: no such file or directory, open './polls/bot_1.json'
0|CSGOTrad | (node:29359) [DEP0013] DeprecationWarning: Calling an asynchronous                                                                                                                                                              function without callback is deprecated.
0|CSGOTrad | Error: ENOENT: no such file or directory, open './polls/bot_1.json'
0|CSGOTrad | (node:29393) [DEP0013] DeprecationWarning: Calling an asynchronous                                                                                                                                                              function without callback is deprecated.
0|CSGOTrad | Error: ENOENT: no such file or directory, open './polls/bot_1.json'
0|CSGOTrad | (node:29403) [DEP0013] DeprecationWarning: Calling an asynchronous                                                                                                                                                              function without callback is deprecated.
0|CSGOTrad | Error: ENOENT: no such file or directory, open './polls/bot_1.json'
0|CSGOTrad | (node:29453) [DEP0013] DeprecationWarning: Calling an asynchronous                                                                                                                                                              function without callback is deprecated.
0|CSGOTrad | Error: ENOENT: no such file or directory, open './polls/bot_1.json'

/root/.pm2/logs/CSGOTrading-out-0.log last 15 lines:
0|CSGOTrad | Bot (bot_1) has been logged-in.
0|CSGOTrad | [!] Website server is online.
0|CSGOTrad | [!] Socket server is online.
0|CSGOTrad | [!] Prices are updated.
0|CSGOTrad | Bot (bot_1) has been logged-in.
0|CSGOTrad | [!] Website server is online.
0|CSGOTrad | [!] Socket server is online.
0|CSGOTrad | [!] Prices are updated.
0|CSGOTrad | Steam Guard App Code: [FloatChecker:Progress] Starting to acquire f                                                                                                                                                             loats for bot "bot_1". This can take a while if you have a lot of items.
0|CSGOTrad | [ '11922203747' ]
0|CSGOTrad | [ '11912248505' ]
0|CSGOTrad | [FloatChecker:Progress] Done floats for bot "bot_1".
0|CSGOTrad | [!] All bots online.
0|CSGOTrad | [ '11926026853', '11920061559' ]
0|CSGOTrad | [ '11926026853', '11920061559' ]

0|CSGOTrad | [ '11908908146' ]`

**Comment by pepzwee** [comment]
Okay, join the SteamApis Discord and PM me there. I'll help you figure it out once I have time - I'll have some time in 4-6 hours probably.

**Comment by F4ri0us** [comment]
I'm connected to your Discord.

**Comment by F4ri0us** [comment]
@pepzwee I'm still connected to your Discord but I still have no answers to the problem ...

**Comment by FreddyFish** [comment]
Try to use the original prices.js file.
Also go here, and log in with your bot account.  Can you generate a new key?
http://steamcommunity.com/dev/apikey

**Comment by F4ri0us** [comment]
Hello @FreddyFish ,

I have created a new API key on Steam but I still have the same problem.
For the file price.js, I made all the changes. (https://github.com/pepzwee/node-csgo-web-tradebot/commit/1bda843ddee5179c3d54b4d409d0f8ba9f58c4a5)

0|CSGOTrad | (node:3888) [DEP0013] DeprecationWarning: Calling an asynchronous f                                                                                                                                                             unction without callback is deprecated.
0|CSGOTrad | Error: ENOENT: no such file or directory, open './polls/bot_1.json'
0|CSGOTrad | Error: Cannot log onto steamcommunity.com without first being conne                                                                                                                                                             cted to Steam network
0|CSGOTrad |     at SteamUser.webLogOn (/var/www/vhosts/xxxxxxxx/httpdocs                                                                                                                                                             /node_modules/steam-user/components/web.js:9:9)
0|CSGOTrad |     at Object.keys.forEach (/var/www/vhosts/xxxxxxxxxx/httpdoc                                                                                                                                                             s/lib/bots.js:125:35)
0|CSGOTrad |     at Array.forEach (<anonymous>)
0|CSGOTrad |     at Trade.reloadBotSessions (/var/www/vhosts/xxxxxxxxxxxxx/htt                                                                                                                                                             pdocs/lib/bots.js:124:33)
0|CSGOTrad |     at Timeout.setInterval [as _onTimeout] (/var/www/vhosts/xxxxxxxxxx/httpdocs/lib/index.js:24:32)
0|CSGOTrad |     at ontimeout (timers.js:469:11)
0|CSGOTrad |     at tryOnTimeout (timers.js:304:5)
0|CSGOTrad |     at Timer.listOnTimeout (timers.js:264:5)
0|CSGOTrad | (node:3987) [DEP0013] DeprecationWarning: Calling an asynchronous f                                                                                                                                                             unction without callback is deprecated.
0|CSGOTrad | Error: ENOENT: no such file or directory, open './polls/bot_1.json'
0|CSGOTrad | (node:4169) [DEP0013] DeprecationWarning: Calling an asynchronous f                                                                                                                                                             unction without callback is deprecated.
0|CSGOTrad | Error: ENOENT: no such file or directory, open './polls/bot_1.json'

/root/.pm2/logs/CSGOTrading-out-0.log last 15 lines:
0|CSGOTrad | [!] Socket server is online.
0|CSGOTrad | [!] Prices are updated.
0|CSGOTrad | Steam Guard App Code: [FloatChecker:Progress] Starting to acquire f                                                                                                                                                             loats for bot "bot_1". This can take a while if you have a lot of items.
0|CSGOTrad | [FloatChecker:Progress] Done floats for bot "bot_1".
0|CSGOTrad | [!] All bots online.
0|CSGOTrad | Bot (bot_1) has been logged-in.
0|CSGOTrad | [!] Website server is online.
0|CSGOTrad | [!] Socket server is online.
0|CSGOTrad | [!] Prices are updated.
0|CSGOTrad | Bot (bot_1) has been logged-in.
0|CSGOTrad | [!] Website server is online.
0|CSGOTrad | [!] Socket server is online.
0|CSGOTrad | [!] Prices are updated.
0|CSGOTrad | Steam Guard App Code: [FloatChecker:Progress] Starting to acquire f                                                                                                                                                             loats for bot "bot_1". This can take a while if you have a lot of items.
0|CSGOTrad | [ '11906615392' ]

**Comment by pepzwee** [comment]
Needed to create ``polls/bot_1.json`` file.

**Comment by jubel02** [comment]
Kk i have same problem so i created new file polls/bot_1.json. But is that file should be an empty or?
Anyone could help me setup this website?

**Comment by pepzwee** [comment]
@jubel02 the file contents should be like this ``{}``
